export const DECK_LIMITS = Object.freeze({
	NAME_MAX: 100,
	DESCRIPTION_MAX: 500,
	WORD_MAX: 200,
	MEANING_MAX: 1000,
	IPA_MAX: 100,
	PART_OF_SPEECH_MAX: 50,
	EN_EXAMPLE_MAX: 500,
	VI_EXAMPLE_MAX: 500,
	TAG_MAX: 50,
	TAG_COUNT_MAX: 20,
	BULK_FROM_VOCAB_MAX: 50,
	DECK_LIST_PAGE_SIZE_MAX: 50,
	CARD_LIST_PAGE_SIZE_MAX: 100,
	FOLDER_NAME_MAX: 100,
	FOLDER_LIST_PAGE_SIZE_MAX: 50,
});

export const DECK_VISIBILITY = Object.freeze({
	PRIVATE: "private",
	PUBLIC: "public",
});

export const CARD_STATUS = Object.freeze({
	KNOWN: "known",
	UNKNOWN: "unknown",
});

export const CARD_STATUS_VALUES = Object.freeze([
	CARD_STATUS.KNOWN,
	CARD_STATUS.UNKNOWN,
]);
