import "dotenv/config";
import mongoose from "mongoose";
import { CONNECT_DB } from "@server/config/mongodb";
import { Rewrite } from "@server/models/writing/Rewrite";
import { createLesson } from "@server/services/rewriteService";

/**
 * Seed 60 Rewrite (paraphrasing) lessons: 20 topics × 3 levels.
 * Each lesson holds 10-15 unique target sentences sized to the level:
 *   - beginner    → 10 simple sentences
 *   - intermediate → 12 compound/varied sentences
 *   - advanced    → 15 complex/idiomatic sentences
 *
 * Follows the real admin flow (rewriteService.createLesson → createWriting → prepareRewrite).
 *
 * Idempotent: skip if a lesson with the same title already exists (unless FORCE=1).
 *
 * Usage:
 *   pnpm dlx @babel/node src/commands/seedRewrite.js
 *   FORCE=1 pnpm dlx @babel/node src/commands/seedRewrite.js
 */

const FORCE = process.env.FORCE === "1";

const LESSONS = [
  // ─── 1. personal_communication ───
  {
    topic: "personal_communication",
    level: "beginner",
    title: "Family and Friends — Basic Paraphrasing",
    description: "Rewrite short everyday sentences about family and friends.",
    sentences: [
      "My mother calls me every Sunday evening.",
      "I have two brothers and one younger sister.",
      "We often talk about our plans for the weekend.",
      "My best friend lives next door to my house.",
      "She sends me a message every morning.",
      "I call my grandparents every weekend.",
      "We are going to a birthday party tomorrow.",
      "He thanked me for helping with the homework.",
      "My cousin visits us once a month.",
      "Our family has dinner together every evening.",
    ],
  },
  {
    topic: "personal_communication",
    level: "intermediate",
    title: "Conversations and Social Interactions",
    description:
      "Paraphrase sentences about social interactions and meaningful conversations.",
    sentences: [
      "Although we hadn't seen each other for years, we picked up the conversation as if no time had passed.",
      "She mentioned that she was considering moving to a new city for her career.",
      "Communicating openly with your partner is essential to maintaining a healthy relationship.",
      "He apologized for missing the meeting and promised to make up for it.",
      "My colleague is always the first to congratulate me on my achievements.",
      "I asked her for advice because she has more experience than I do.",
      "The two friends decided to settle their disagreement over a cup of coffee.",
      "Many young people prefer texting to making phone calls.",
      "It can be difficult to express your true feelings in a foreign language.",
      "We arranged to meet at the café after work.",
      "She has a habit of interrupting people in the middle of their sentences.",
      "The new app makes it easy to stay in touch with family who live abroad.",
    ],
  },
  {
    topic: "personal_communication",
    level: "advanced",
    title: "Nuances of Interpersonal Communication",
    description:
      "Rephrase complex sentences about communication, empathy, and interpersonal dynamics.",
    sentences: [
      "The capacity to convey empathy without resorting to platitudes is a hallmark of emotional maturity.",
      "Misinterpretations frequently arise when cultural context is overlooked in cross-border correspondence.",
      "Active listening, as opposed to merely waiting for one's turn to speak, fundamentally transforms a dialogue.",
      "His reluctance to disclose his reservations stemmed from a deeply ingrained fear of confrontation.",
      "Establishing rapport with strangers often hinges on small, unspoken signals rather than overt declarations.",
      "Tactful silence can be more eloquent than the most carefully chosen words.",
      "The art of conversation lies in striking the delicate balance between speaking and listening.",
      "Diplomatic language often serves to soften the impact of difficult news.",
      "A talented mediator can find common ground in seemingly intractable disputes.",
      "Body language often betrays sentiments that words attempt to conceal.",
      "Genuine compliments retain their power precisely because they are sparingly distributed.",
      "Cross-generational communication requires sensitivity to differing communicative norms.",
      "The phrase 'reading between the lines' captures something essential about sophisticated discourse.",
      "Misunderstandings, once entrenched, often prove remarkably resistant to subsequent clarification.",
      "Vulnerability, when offered authentically, can rapidly deepen otherwise superficial relationships.",
    ],
  },

  // ─── 2. everyday_life ───
  {
    topic: "everyday_life",
    level: "beginner",
    title: "Daily Routines and Habits",
    description: "Rewrite simple sentences about daily activities.",
    sentences: [
      "I wake up at six o'clock every morning.",
      "She walks to school because it is very close.",
      "We watch TV together after dinner.",
      "He goes to bed at ten o'clock.",
      "I always eat breakfast before going to work.",
      "My sister cleans her room every Sunday.",
      "We go shopping at the weekend.",
      "They have lunch at the same restaurant every day.",
      "I usually drink coffee in the morning.",
      "He takes the dog for a walk every evening.",
    ],
  },
  {
    topic: "everyday_life",
    level: "intermediate",
    title: "Modern Living and Time Management",
    description: "Paraphrase sentences about lifestyle, schedules, and habits.",
    sentences: [
      "Managing time effectively requires both planning and the discipline to stick to your plan.",
      "Most people find that they are more productive in the early hours of the morning.",
      "Spending too much time on social media can leave you feeling drained rather than refreshed.",
      "Setting small daily goals is often more effective than relying on grand resolutions.",
      "Many city dwellers find their evenings consumed by errands rather than relaxation.",
      "The habit of writing things down has helped me remember important appointments.",
      "Skipping breakfast may save time but often backfires by mid-morning.",
      "Reading a few pages of a book before bed has noticeably improved my sleep.",
      "Cooking your own meals usually works out cheaper than ordering takeout every night.",
      "A short walk after lunch can be surprisingly effective at restoring focus.",
      "Many families struggle to find time to sit down for a meal together.",
      "Keeping a tidy workspace seems to make everyday tasks feel less overwhelming.",
    ],
  },
  {
    topic: "everyday_life",
    level: "advanced",
    title: "Reflections on Modern Lifestyles",
    description: "Rephrase nuanced observations about everyday modern life.",
    sentences: [
      "The relentless pace of urban life has rendered moments of genuine repose almost a luxury.",
      "Habits, once entrenched, exert a subtle but persistent influence over daily decisions.",
      "Disconnecting from digital devices periodically can yield surprising improvements in concentration.",
      "Minimalism, while increasingly popular, demands a level of intentionality many find uncomfortable.",
      "The cumulative effect of seemingly trivial choices often shapes long-term well-being.",
      "Modern rituals — coffee at sunrise, evening commutes — quietly structure the architecture of daily life.",
      "The boundary between leisure and labour has grown increasingly porous in the era of remote work.",
      "Routine, far from being the enemy of creativity, often furnishes the scaffolding upon which it thrives.",
      "Domestic tasks, however mundane, are frequently sites of unspoken negotiation between household members.",
      "Punctuality is regarded in some cultures as a virtue, in others as an unnecessary social rigidity.",
      "The proliferation of convenience services has perversely added new layers of decision-fatigue to ordinary life.",
      "A well-considered morning routine can pre-empt the small frustrations that otherwise compound throughout the day.",
      "Burnout often announces itself not in a dramatic collapse but in a gradual erosion of small joys.",
      "Solitude, when chosen rather than imposed, can be one of life's most restorative experiences.",
      "The proverbial rat race often consists less of moving forward than of merely keeping pace.",
    ],
  },

  // ─── 3. transportation_travel ───
  {
    topic: "transportation_travel",
    level: "beginner",
    title: "Getting Around — Basics",
    description: "Rewrite simple sentences about transport and travel.",
    sentences: [
      "I take the bus to work every day.",
      "She wants to visit Japan next summer.",
      "The train arrives at the station at eight o'clock.",
      "We are going to the airport tomorrow.",
      "He drives a small white car.",
      "I usually ride my bike to school.",
      "The taxi driver was very friendly.",
      "They are flying to Singapore next week.",
      "She always takes the same route home.",
      "The bus is faster than walking.",
    ],
  },
  {
    topic: "transportation_travel",
    level: "intermediate",
    title: "Travel Plans and Public Transport",
    description:
      "Paraphrase sentences about journeys, traffic, and travel logistics.",
    sentences: [
      "Booking your tickets several weeks in advance usually results in significant savings.",
      "Heavy traffic during rush hour can easily double the length of your commute.",
      "Many travelers prefer trains to airplanes because of the more spacious seating.",
      "Visiting a new country often involves more careful planning than people initially expect.",
      "Public transport in this city has improved considerably over the last decade.",
      "Renting a car can give you more flexibility than relying on tours.",
      "The new high-speed line cuts travel time between the two cities in half.",
      "Cycling lanes have made it safer to commute by bike in the city centre.",
      "Travellers are advised to check visa requirements before purchasing flights.",
      "Driving in unfamiliar cities is often more stressful than locals realise.",
      "Some hotels offer free shuttle services to and from the airport.",
      "Backpacking has become a popular way for young people to see the world.",
    ],
  },
  {
    topic: "transportation_travel",
    level: "advanced",
    title: "Tourism and Modern Mobility",
    description:
      "Rephrase complex sentences about transport infrastructure and travel culture.",
    sentences: [
      "The proliferation of low-cost carriers has democratised international travel for an entire generation.",
      "Sustainable tourism initiatives seek to balance economic benefits with environmental preservation.",
      "Congestion in metropolitan areas continues to undermine the efficiency of urban transit networks.",
      "Backpacking through unfamiliar regions can be as exhausting as it is enlightening.",
      "Investment in high-speed rail has yielded dividends in both productivity and reduced emissions.",
      "Cruise tourism, despite its popularity, has come under scrutiny for its environmental footprint.",
      "The romanticism of the open road has long been a recurring motif in travel literature.",
      "Regulatory inconsistencies across jurisdictions complicate the deployment of autonomous vehicles.",
      "Travel often does more than relocate the body — it dislocates inherited assumptions.",
      "Aviation's contribution to climate change presents an uncomfortable truth for environmentally-minded travellers.",
      "Slow travel, in deliberate opposition to whirlwind itineraries, prioritises immersion over coverage.",
      "The decay of regional rail networks has hollowed out the connectivity of smaller towns.",
      "Geopolitical tensions can render previously routine border crossings unexpectedly fraught.",
      "The ethics of voluntourism have come under increasing scrutiny from critics in the development sector.",
      "Mass tourism has fundamentally altered the social fabric of many historically tranquil destinations.",
    ],
  },

  // ─── 4. school_education ───
  {
    topic: "school_education",
    level: "beginner",
    title: "Classroom and Studies",
    description: "Rewrite simple sentences about school and learning.",
    sentences: [
      "My favorite subject is mathematics.",
      "The teacher asks us to do our homework every day.",
      "I usually study with my friends after class.",
      "She has English class on Monday morning.",
      "The school library has many books.",
      "He always gets good grades in science.",
      "I like reading books in my free time.",
      "The students wear blue uniforms.",
      "We have lunch break at twelve.",
      "My new teacher is very kind.",
    ],
  },
  {
    topic: "school_education",
    level: "intermediate",
    title: "Studying and Academic Life",
    description:
      "Paraphrase sentences about studying, exams, and university life.",
    sentences: [
      "Preparing for exams becomes far less stressful when you start reviewing material earlier in the term.",
      "Group projects often teach students as much about teamwork as they do about the subject matter.",
      "Many universities now offer flexible online courses for students who work full-time.",
      "The quality of a school is sometimes more about the teachers than the facilities.",
      "Studying abroad can offer experiences that no textbook can replicate.",
      "The right learning environment can dramatically improve a student's motivation.",
      "Many parents struggle to balance helping with homework and respecting their child's independence.",
      "Modern classrooms increasingly incorporate technology into everyday lessons.",
      "Standardised tests have been criticised for narrowing the focus of education.",
      "Extracurricular activities often shape a student's personality as much as academics do.",
      "Bilingual education has become more widely accepted in many countries.",
      "Tutors can bridge the gap when a student falls behind in a particular subject.",
    ],
  },
  {
    topic: "school_education",
    level: "advanced",
    title: "Education Systems and Pedagogy",
    description:
      "Rephrase complex sentences about education theory and practice.",
    sentences: [
      "Critical thinking should be cultivated from an early age rather than treated as an advanced elective.",
      "Standardised testing, though widely used, fails to capture the full breadth of a student's abilities.",
      "Pedagogical approaches that emphasise inquiry tend to produce more independent learners.",
      "Disparities in educational resources continue to perpetuate cycles of social inequality.",
      "Lifelong learning has become not merely an aspiration but an economic necessity.",
      "The Socratic method, when skilfully deployed, can transform passive listeners into active thinkers.",
      "Educational technology promises efficiency yet risks marginalising the irreplaceable human element of teaching.",
      "Curriculum reform tends to lag behind the rapid evolution of the knowledge it purports to convey.",
      "The hidden curriculum — what schools teach implicitly — often shapes character more than explicit instruction.",
      "University rankings, despite their influence, oversimplify the complex experience of higher education.",
      "Vocational pathways have historically suffered from a perception of inferiority relative to academic tracks.",
      "Tenure systems were designed to protect academic freedom but increasingly face questions about accountability.",
      "The gamification of learning carries both pedagogical promise and the risk of trivialisation.",
      "Educational philosophies oscillate between liberal arts traditions and demands for narrowly utilitarian skills.",
      "Parental over-involvement, while well-intentioned, can stunt the development of autonomous problem-solving.",
    ],
  },

  // ─── 5. work_business ───
  {
    topic: "work_business",
    level: "beginner",
    title: "Office and Daily Work",
    description: "Rewrite simple sentences about jobs and office life.",
    sentences: [
      "I work in a small office near my house.",
      "My boss is very kind and helpful.",
      "We have a team meeting every Monday morning.",
      "She finishes work at five o'clock.",
      "He sends emails to clients all day.",
      "The new employee started yesterday.",
      "I usually have lunch at the office cafeteria.",
      "We work from home on Fridays.",
      "My colleagues are very friendly.",
      "The company is closed on weekends.",
    ],
  },
  {
    topic: "work_business",
    level: "intermediate",
    title: "Workplace and Productivity",
    description:
      "Paraphrase sentences about office culture, deadlines, and teamwork.",
    sentences: [
      "Working remotely has changed how teams collaborate across different time zones.",
      "A well-prepared presentation can significantly increase your chances of being promoted.",
      "Many employees find that small breaks throughout the day improve their overall productivity.",
      "Building a strong professional network often opens doors that résumés alone cannot.",
      "The company invests heavily in training new staff during their first year.",
      "Negotiating a salary raise requires preparation and confidence.",
      "Many startups offer flexible working hours to attract young talent.",
      "Effective time management is one of the most underrated workplace skills.",
      "Open-plan offices can encourage collaboration but also reduce focus.",
      "Performance reviews provide valuable feedback when conducted constructively.",
      "Many young professionals are choosing freelancing over traditional employment.",
      "Workplace diversity has been shown to drive innovation across industries.",
    ],
  },
  {
    topic: "work_business",
    level: "advanced",
    title: "Corporate Strategy and Leadership",
    description:
      "Rephrase nuanced sentences about business, leadership, and innovation.",
    sentences: [
      "Visionary leadership is distinguished less by charisma than by the capacity to align teams around a shared purpose.",
      "Companies that fail to adapt to disruptive technologies frequently find themselves rendered obsolete within a decade.",
      "Cultivating a culture of psychological safety has emerged as a prerequisite for sustained innovation.",
      "Quarterly earnings pressures can incentivise short-term thinking at the expense of long-term value creation.",
      "Strategic acquisitions often hinge as much on cultural fit as on financial synergies.",
      "The gig economy has reconfigured the traditional employer-employee compact in ways still being negotiated.",
      "Burnout in high-performing teams often masquerades as productivity until it suddenly does not.",
      "Stakeholder capitalism challenges the doctrine that shareholder return must be the sole metric of corporate success.",
      "Internal mobility programs can reduce attrition by offering employees growth without departure.",
      "Diversity, equity, and inclusion initiatives produce measurable returns when integrated into core strategy.",
      "The proliferation of business buzzwords often obscures rather than clarifies actual operational priorities.",
      "Corporate transparency, once optional, has become indispensable in the era of pervasive social-media scrutiny.",
      "Disruption typically originates not from incumbents but from outsiders unencumbered by legacy assumptions.",
      "The leadership pipeline often suffers from systemic biases that favour familiar profiles over diverse talent.",
      "Mergers tend to fail not for lack of strategic logic but for failure to manage the human integration.",
    ],
  },

  // ─── 6. public_services ───
  {
    topic: "public_services",
    level: "beginner",
    title: "Using Public Services",
    description: "Rewrite simple sentences about everyday public services.",
    sentences: [
      "I went to the post office to send a letter.",
      "The library is open from eight to nine every day.",
      "He paid his electricity bill at the bank.",
      "She is renewing her driver's license today.",
      "The hospital is near the train station.",
      "I called the police because I lost my bag.",
      "We registered our new address at the city hall.",
      "The buses run every fifteen minutes here.",
      "The school bus picks up the children at seven.",
      "Many libraries also offer free Wi-Fi.",
    ],
  },
  {
    topic: "public_services",
    level: "intermediate",
    title: "Civic Life and Bureaucracy",
    description:
      "Paraphrase sentences about interacting with government and city services.",
    sentences: [
      "Applying for a passport usually involves filling in several forms and waiting in line.",
      "Many cities have introduced online portals to make basic services more accessible.",
      "Tax season is often stressful because of the volume of paperwork involved.",
      "Public libraries continue to serve as important community hubs in many neighbourhoods.",
      "The wait at the immigration office can be reduced by booking an appointment online.",
      "Local councils often hold public meetings to discuss neighbourhood concerns.",
      "Filing for unemployment benefits has become much faster since the digital reform.",
      "Many cities are improving access for people with disabilities at public buildings.",
      "Garbage collection schedules vary considerably between different districts.",
      "The fire department also offers free safety inspections for old buildings.",
      "Online portals now let citizens track the progress of their applications in real time.",
      "Volunteers play a critical role in maintaining many community parks.",
    ],
  },
  {
    topic: "public_services",
    level: "advanced",
    title: "Public Administration and Civic Engagement",
    description:
      "Rephrase complex sentences about governance, regulation, and civic participation.",
    sentences: [
      "Bureaucratic inefficiency, while routinely lampooned, often masks a deeper problem of underfunded institutions.",
      "Digital transformation initiatives in public administration have yielded uneven results across regions.",
      "Citizens increasingly expect transparent reporting on how their tax contributions are utilised.",
      "Public-private partnerships can accelerate infrastructure delivery but raise questions about accountability.",
      "The capacity to navigate complex government services has itself become a form of social privilege.",
      "Devolution of central authority to local councils sometimes accentuates rather than alleviates inequalities.",
      "Civil-service reform tends to founder where political incentives reward continuity rather than restructuring.",
      "Public consultation, when conducted as mere ritual, can erode rather than reinforce democratic legitimacy.",
      "The redefinition of essential services in the digital age has lagged behind technological change.",
      "Accessibility remains a persistent gap between policy aspiration and on-the-ground delivery of services.",
      "The professionalisation of advocacy has shifted civic engagement away from spontaneous mobilisation.",
      "Open-data initiatives promise accountability but presuppose a public capable of interpreting raw statistics.",
      "Government efficiency drives invariably collide with the institutional inertia they aim to overcome.",
      "Public trust in institutions, once eroded, cannot be restored merely through better communication.",
      "The architecture of public space subtly shapes how citizens experience their relationship to the state.",
    ],
  },

  // ─── 7. health_medicine ───
  {
    topic: "health_medicine",
    level: "beginner",
    title: "Health and the Doctor",
    description:
      "Rewrite simple sentences about feeling sick and visiting the doctor.",
    sentences: [
      "I have a headache and I need to rest.",
      "She drinks a lot of water every day.",
      "The doctor told me to take this medicine after lunch.",
      "He has a high fever and a sore throat.",
      "Walking every morning is good for your health.",
      "The nurse gave me an injection.",
      "I went to the pharmacy to buy aspirin.",
      "She visits the dentist twice a year.",
      "My grandmother takes medicine for her blood pressure.",
      "Getting enough sleep is very important.",
    ],
  },
  {
    topic: "health_medicine",
    level: "intermediate",
    title: "Healthcare and Wellness",
    description:
      "Paraphrase sentences about clinics, prevention, and healthy habits.",
    sentences: [
      "Regular exercise can significantly reduce the risk of chronic illnesses later in life.",
      "Patients are often advised to seek a second opinion before agreeing to surgery.",
      "Health insurance remains a major financial concern for many families.",
      "Mental health is finally receiving the attention it has long deserved.",
      "Doctors recommend reducing sugar intake to protect against diabetes.",
      "Many people overlook the importance of regular dental check-ups.",
      "Hospitals have begun introducing more patient-friendly waiting areas.",
      "The new vaccine has been distributed to clinics across the country.",
      "Telemedicine has made it easier for people in remote areas to consult specialists.",
      "Stress management techniques have become a core part of preventive care.",
      "Doctors increasingly encourage patients to track their own health data.",
      "Hand hygiene remains one of the simplest and most effective public-health measures.",
    ],
  },
  {
    topic: "health_medicine",
    level: "advanced",
    title: "Medical Research and Public Health",
    description:
      "Rephrase nuanced sentences about medicine, biotechnology, and healthcare policy.",
    sentences: [
      "Personalised medicine, though still in its infancy, promises to tailor treatments to individual genetic profiles.",
      "Vaccination programmes have averted countless deaths, yet vaccine hesitancy continues to undermine public health.",
      "Antibiotic resistance is emerging as one of the most pressing threats to modern medicine.",
      "Equitable access to healthcare remains an unresolved challenge, even in affluent societies.",
      "Translating biomedical research into clinical practice is often a far slower process than the public imagines.",
      "The placebo effect, far from being trivial, has reshaped how clinical trials are designed.",
      "Pandemic preparedness exposed structural deficiencies that decades of cost-cutting had quietly accumulated.",
      "Mental healthcare provision continues to lag dramatically behind treatment of physical illness.",
      "The pharmaceutical industry's pricing strategies routinely test the limits of public tolerance.",
      "Genomic data promises diagnostic precision but raises profound questions about privacy and consent.",
      "Health inequities tend to compound across generations in ways that single interventions cannot address.",
      "The rise of antimicrobial resistance constitutes a slow-motion catastrophe largely overshadowed by acute crises.",
      "Population-level interventions often achieve more than individually-targeted treatments for shared conditions.",
      "End-of-life care raises ethical questions that medicine alone is poorly equipped to resolve.",
      "Healthcare workers face cumulative trauma that institutions have only recently begun to acknowledge systemically.",
    ],
  },

  // ─── 8. shopping_money ───
  {
    topic: "shopping_money",
    level: "beginner",
    title: "Shopping and Prices",
    description: "Rewrite simple sentences about shopping and paying.",
    sentences: [
      "This dress is too expensive for me.",
      "I bought some apples at the market this morning.",
      "She paid for the bill with her credit card.",
      "The supermarket is having a big sale today.",
      "He keeps his money in a small leather wallet.",
      "I always check the price before I buy something.",
      "My mother prefers to shop at the local market.",
      "We need to save money to buy a new sofa.",
      "The cashier gave me the wrong change.",
      "She wants to buy a new pair of shoes.",
    ],
  },
  {
    topic: "shopping_money",
    level: "intermediate",
    title: "Consumer Behavior and Budgeting",
    description:
      "Paraphrase sentences about shopping habits, sales, and personal finance.",
    sentences: [
      "Many shoppers wait for end-of-season sales before purchasing high-priced items.",
      "Sticking to a monthly budget is easier when you track every small expense.",
      "Online shopping has made it more convenient to compare prices across different stores.",
      "Impulse purchases often turn out to be the items we regret buying the most.",
      "Loyalty programmes can deliver real savings, provided you would have shopped there anyway.",
      "Avoiding credit-card debt is one of the most underrated financial habits.",
      "Reading product reviews has become a routine step before most major purchases.",
      "Many young consumers are willing to pay a premium for ethically-sourced goods.",
      "Cashless payment apps have changed the way people split bills at restaurants.",
      "Bulk buying can save money but only if you actually use what you buy.",
      "Subscription services are easy to forget about and surprisingly hard to cancel.",
      "Comparing insurance policies annually often reveals significant savings.",
    ],
  },
  {
    topic: "shopping_money",
    level: "advanced",
    title: "Economics of Consumption and Finance",
    description:
      "Rephrase complex sentences about consumer culture and personal finance.",
    sentences: [
      "Compound interest, often described as the eighth wonder of the world, can either accelerate wealth or amplify debt.",
      "The shift toward cashless transactions has restructured both consumer behaviour and merchant economics.",
      "Predatory lending practices disproportionately affect those least able to absorb financial setbacks.",
      "Brand loyalty is increasingly mediated through digital experiences rather than physical interactions.",
      "Diversifying one's investment portfolio is a fundamental principle of mitigating downside risk.",
      "Behavioural economics has illuminated the systematic biases that shape ostensibly rational choices.",
      "Luxury markets thrive precisely on the artificial scarcity that mass-market efficiency cannot replicate.",
      "Inflation acts as a regressive tax, weighing most heavily on those with the smallest cash buffers.",
      "Financial literacy education tends to focus on individual responsibility while underplaying structural pressures.",
      "The democratisation of investing through commission-free platforms carries both benefits and underappreciated risks.",
      "Cryptocurrencies have introduced novel asset classes whose long-term role remains genuinely contested.",
      "Consumer-protection regulation struggles to keep pace with the rapid evolution of financial products.",
      "Spending patterns often reveal psychological dispositions that the spenders themselves remain unaware of.",
      "Retirement planning has shifted from defined benefit to defined contribution, transferring risk to individuals.",
      "The marketing of aspirational lifestyles encourages consumption patterns that diverge from genuine well-being.",
    ],
  },

  // ─── 9. food_drink ───
  {
    topic: "food_drink",
    level: "beginner",
    title: "Food and Drinks Basics",
    description: "Rewrite simple sentences about meals and beverages.",
    sentences: [
      "I eat rice and vegetables for dinner.",
      "He doesn't like spicy food.",
      "We usually drink water with our meals.",
      "She loves chocolate ice cream.",
      "My father drinks tea every morning.",
      "I am cooking fried noodles for lunch.",
      "There is a new bakery on this street.",
      "We had pho for breakfast today.",
      "He buys fresh bread every morning.",
      "Mangoes are my favourite fruit.",
    ],
  },
  {
    topic: "food_drink",
    level: "intermediate",
    title: "Cooking and Dining Out",
    description:
      "Paraphrase sentences about cooking, restaurants, and dietary choices.",
    sentences: [
      "Eating a balanced diet is one of the simplest ways to maintain good health.",
      "Many restaurants now offer plant-based options to accommodate changing customer preferences.",
      "Cooking at home is generally cheaper and healthier than dining out every day.",
      "The chef recommended pairing the steak with a glass of red wine.",
      "Fast food has become a staple of weekday lunches for office workers.",
      "Many people enjoy trying authentic street food when travelling abroad.",
      "Soaking the rice for ten minutes before cooking can improve the texture.",
      "Cafés have become popular workspaces for freelancers and students alike.",
      "Reading the ingredient label has become a routine habit for health-conscious shoppers.",
      "Many restaurants offer cooking classes that teach customers regional specialities.",
      "Tipping customs vary widely across different countries and cuisines.",
      "Seasonal produce often tastes better and is usually cheaper than imported alternatives.",
    ],
  },
  {
    topic: "food_drink",
    level: "advanced",
    title: "Gastronomy and Food Culture",
    description:
      "Rephrase nuanced sentences about cuisine, sustainability, and food systems.",
    sentences: [
      "Locally-sourced ingredients lend authenticity to traditional dishes that mass production rarely matches.",
      "Industrial agriculture, while highly productive, has imposed substantial costs on biodiversity.",
      "Fine dining transcends mere nourishment, functioning as a curated sensory experience.",
      "Fermented foods have re-entered mainstream cuisine on the back of growing interest in gut health.",
      "Food deserts in low-income neighbourhoods perpetuate cycles of poor nutrition and chronic illness.",
      "The provenance of ingredients now figures as prominently on menus as the preparation method itself.",
      "Culinary nationalism oversimplifies cuisines that are in reality the product of centuries of exchange.",
      "Plant-based meat substitutes have shifted from niche curiosities to mainstream supermarket items.",
      "Wine appreciation, once the preserve of aristocrats, has been democratised through inexpensive but ambitious producers.",
      "Heritage grains, long abandoned for industrial varieties, are returning to the attention of artisanal bakers.",
      "Food waste at the household level continues to outstrip waste at the production stage in many developed countries.",
      "The chef-as-celebrity phenomenon has elevated cooking from craft to cultural commentary.",
      "Globalised supply chains have made out-of-season produce ubiquitous yet far less remarkable.",
      "Sourdough revival illustrates how artisanal food culture can flourish alongside industrial mass production.",
      "The ethical implications of meat consumption have become impossible to ignore in any serious conversation about food.",
    ],
  },

  // ─── 10. entertainment_leisure ───
  {
    topic: "entertainment_leisure",
    level: "beginner",
    title: "Fun and Free Time",
    description:
      "Rewrite simple sentences about hobbies and leisure activities.",
    sentences: [
      "I like to play football on weekends.",
      "She watches movies with her sister every Saturday.",
      "He reads comic books before going to bed.",
      "We listen to music while doing homework.",
      "My brother plays video games every evening.",
      "I want to go to the cinema this weekend.",
      "She enjoys taking photos in the park.",
      "We had a picnic in the countryside last Sunday.",
      "He collects vintage stamps as a hobby.",
      "Many children love going to amusement parks.",
    ],
  },
  {
    topic: "entertainment_leisure",
    level: "intermediate",
    title: "Hobbies, Movies, and Music",
    description:
      "Paraphrase sentences about hobbies, films, and the entertainment industry.",
    sentences: [
      "Streaming services have completely changed the way people watch movies and television.",
      "Many young people now spend more time gaming than watching traditional television.",
      "Live concerts can offer a sense of community that recorded music simply cannot match.",
      "Picking up a new hobby is a great way to relieve stress after a long workweek.",
      "Family board games are making a surprising comeback in the era of smartphones.",
      "Many concert venues now allow audiences to record short clips during performances.",
      "Reading clubs offer a chance to discuss books in depth with like-minded readers.",
      "Cinemas have invested heavily in luxury seating to compete with home streaming.",
      "Sports bars have become popular destinations for fans without home subscriptions.",
      "Many museums now offer virtual tours that visitors can explore from home.",
      "Festival tickets often sell out within minutes of going on sale.",
      "Travelling for live concerts has become a common form of fan tourism.",
    ],
  },
  {
    topic: "entertainment_leisure",
    level: "advanced",
    title: "Media, Pop Culture, and the Arts",
    description:
      "Rephrase complex sentences about entertainment, audiences, and cultural production.",
    sentences: [
      "The algorithmic curation of content has subtly reshaped what audiences are exposed to.",
      "Blockbuster cinema, while commercially dominant, often crowds out narratives that demand more nuanced engagement.",
      "The convergence of gaming and film is producing hybrid forms that defy traditional categorisation.",
      "Cultural institutions increasingly grapple with how to remain relevant to digitally native audiences.",
      "Independent artists now wield distribution power that was unthinkable two decades ago.",
      "Reality television operates on a paradox of authenticity that audiences both believe and disbelieve.",
      "The rise of fan-driven content has blurred the boundary between consumer and creator.",
      "Streaming platforms have weaponised data analytics in ways traditional studios are still struggling to match.",
      "Music criticism has migrated from print magazines to social-media discourse, with mixed consequences.",
      "Theatrical exhibition retains a ceremonial dimension that home viewing has yet to replicate.",
      "Celebrity culture has evolved into a sophisticated industrial complex with its own internal logic.",
      "The democratisation of publishing has both diversified voices and intensified competition for attention.",
      "Esports has emerged as a legitimate spectator sport, complete with sponsorships and stadium events.",
      "The aesthetic vocabulary of social media has begun to inflect mainstream cinema in observable ways.",
      "Cultural production now operates in feedback loops where audience signals shape content almost in real time.",
    ],
  },

  // ─── 11. nature_environment ───
  {
    topic: "nature_environment",
    level: "beginner",
    title: "Nature Around Us",
    description: "Rewrite simple sentences about nature and the weather.",
    sentences: [
      "It is raining today.",
      "We see many birds in the park.",
      "The flowers in the garden are beautiful.",
      "The river runs through the small village.",
      "I love walking in the forest in autumn.",
      "There are many fish in the lake.",
      "The sky is very blue this morning.",
      "We planted a tree in the front yard.",
      "Many butterflies live in this meadow.",
      "The mountain is covered with snow in winter.",
    ],
  },
  {
    topic: "nature_environment",
    level: "intermediate",
    title: "Environment and Sustainability",
    description:
      "Paraphrase sentences about environmental issues and conservation.",
    sentences: [
      "Recycling is one of the easiest ways for individuals to help the environment.",
      "Many countries have introduced policies to reduce single-use plastics.",
      "Climate change has already begun affecting weather patterns around the world.",
      "Protecting forests is essential for preserving global biodiversity.",
      "Electric vehicles have become more affordable in recent years.",
      "Solar panels can significantly reduce a household's electricity bill.",
      "Coral reefs are particularly vulnerable to rising ocean temperatures.",
      "Composting kitchen waste is an easy step toward reducing landfill volume.",
      "Wildlife conservation requires cooperation between governments and local communities.",
      "Many cities have invested in expanding their green spaces.",
      "Eco-tourism aims to support nature while educating visitors.",
      "Air pollution remains a serious health problem in many major cities.",
    ],
  },
  {
    topic: "nature_environment",
    level: "advanced",
    title: "Climate Change and Ecological Stewardship",
    description:
      "Rephrase complex sentences about climate science and conservation policy.",
    sentences: [
      "Anthropogenic emissions have accelerated atmospheric warming at a rate unprecedented in geological records.",
      "Conservation strategies that exclude local communities often fail to deliver sustainable outcomes.",
      "Carbon sequestration technologies, though promising, remain commercially uneconomical at scale.",
      "Biodiversity loss undermines the resilience of ecosystems against compounding environmental shocks.",
      "Transitioning to renewable energy requires coordinated effort across policy, industry, and consumer behaviour.",
      "Climate adaptation has emerged as a complement, not a substitute, for ongoing mitigation efforts.",
      "The framing of environmental problems as individual responsibilities can obscure their structural causes.",
      "Ocean acidification represents a slow-moving crisis whose long-term consequences are still being mapped.",
      "Indigenous land stewardship has demonstrated ecological outcomes that often surpass formal conservation regimes.",
      "Climate policy has been chronically vulnerable to the asymmetry between concentrated costs and diffuse benefits.",
      "Greenwashing erodes consumer trust in environmental claims and slows genuine corporate reform.",
      "Tipping points in earth systems pose risks of nonlinear change that linear models routinely underestimate.",
      "Energy transitions have historically taken decades; the climate crisis demands compression of that timeline.",
      "Environmental justice underscores how ecological harms disproportionately affect already marginalised communities.",
      "Rewilding initiatives challenge traditional conservation by reintroducing ecological agency rather than freezing landscapes.",
    ],
  },

  // ─── 12. science_technology ───
  {
    topic: "science_technology",
    level: "beginner",
    title: "Computers and Phones",
    description: "Rewrite simple sentences about technology in daily life.",
    sentences: [
      "I use my phone to check the weather.",
      "She has a new computer for her work.",
      "He sends messages to his friends every day.",
      "My laptop is faster than my old one.",
      "We watch videos on the tablet at home.",
      "I forgot the password for my email account.",
      "Many children now learn coding at school.",
      "The Wi-Fi in this café is very slow.",
      "She charges her phone every night.",
      "The new app is easy to use.",
    ],
  },
  {
    topic: "science_technology",
    level: "intermediate",
    title: "Tech Innovations and Internet",
    description:
      "Paraphrase sentences about modern technology and the internet.",
    sentences: [
      "Artificial intelligence is already being used to automate many routine tasks.",
      "The Internet of Things connects everyday devices like fridges and watches to the web.",
      "Cybersecurity is becoming an essential skill for almost every business.",
      "Smartphones have replaced cameras, calendars, and even wallets for many people.",
      "Cloud storage makes it easy to access files from any device.",
      "Many companies now use chatbots to handle simple customer questions.",
      "Voice assistants have become a normal part of modern homes.",
      "Online learning platforms now reach millions of students worldwide.",
      "Two-factor authentication has become a basic security measure for online accounts.",
      "Augmented reality apps allow users to preview furniture in their own homes.",
      "Open-source software has played a major role in modern programming.",
      "Privacy settings on social media often go unnoticed by casual users.",
    ],
  },
  {
    topic: "science_technology",
    level: "advanced",
    title: "Frontier Science and Emerging Technologies",
    description:
      "Rephrase nuanced sentences about cutting-edge research and technology policy.",
    sentences: [
      "Quantum computing threatens to render existing cryptographic standards obsolete within a generation.",
      "The ethical implications of generative AI demand frameworks that current legislation is ill-equipped to provide.",
      "CRISPR-based gene editing has opened therapeutic possibilities that border on the science-fictional.",
      "Big-data analytics has shifted scientific inquiry from hypothesis-driven to pattern-driven exploration.",
      "Technological adoption frequently outpaces society's capacity to deliberate on its consequences.",
      "The replication crisis has prompted long-overdue scrutiny of research methodologies across disciplines.",
      "Algorithmic bias often reflects the historical inequities embedded in the data used for training.",
      "Brain-computer interfaces raise profound questions about agency, identity, and consent.",
      "The commercialisation of space has accelerated faster than the regulatory frameworks meant to govern it.",
      "Renewable energy storage remains the critical bottleneck in the decarbonisation of electric grids.",
      "Misinformation propagates more efficiently than its corrections, a structural feature of attention markets.",
      "Synthetic biology promises tailored organisms but rests on biosafety regimes designed for older paradigms.",
      "Digital platforms have inadvertently become geopolitical infrastructure with implications few designers anticipated.",
      "Privacy as traditionally understood may not survive the era of pervasive ambient sensing.",
      "The dual-use nature of emerging technologies complicates any clean separation between civilian and military applications.",
    ],
  },

  // ─── 13. culture_society ───
  {
    topic: "culture_society",
    level: "beginner",
    title: "Culture and Tradition",
    description: "Rewrite simple sentences about culture and customs.",
    sentences: [
      "We celebrate Lunar New Year with our family every year.",
      "She wears traditional clothes on special days.",
      "Many people in our country enjoy folk music.",
      "My grandmother tells us stories from her childhood.",
      "We light incense at the family altar every morning.",
      "Children receive lucky money at Tet.",
      "The festival happens in our village every spring.",
      "He learned to play the traditional drum from his father.",
      "Our family eats sticky rice on special occasions.",
      "She speaks three different languages.",
    ],
  },
  {
    topic: "culture_society",
    level: "intermediate",
    title: "Society and Cultural Identity",
    description:
      "Paraphrase sentences about cultural diversity and societal change.",
    sentences: [
      "Globalisation has made it easier than ever to experience different cultures firsthand.",
      "Many young people now blend traditional values with modern lifestyles.",
      "Festivals play an important role in preserving a community's identity.",
      "Language is one of the most powerful markers of cultural heritage.",
      "Many countries are working to preserve their indigenous languages.",
      "Cross-cultural marriages have become much more common in recent decades.",
      "Traditional craftsmanship is being kept alive by dedicated local artisans.",
      "Migration brings both new opportunities and new challenges for host communities.",
      "Pop culture trends often spread across borders within a matter of weeks.",
      "Older generations sometimes feel disconnected from contemporary social norms.",
      "Diaspora communities maintain traditions that have evolved differently in their home countries.",
      "Many cities now host annual multicultural festivals to celebrate diversity.",
    ],
  },
  {
    topic: "culture_society",
    level: "advanced",
    title: "Multiculturalism and Social Change",
    description:
      "Rephrase complex sentences about identity, integration, and cultural exchange.",
    sentences: [
      "Multicultural societies grapple continuously with the tension between assimilation and preservation of distinct identities.",
      "The commodification of cultural practices risks stripping them of their original significance.",
      "Intergenerational transmission of traditions has been disrupted by the accelerated pace of urbanisation.",
      "Social cohesion frequently rests on shared narratives that are themselves contested and evolving.",
      "Cross-cultural literacy has become an indispensable competency in an interconnected world.",
      "Cultural appropriation debates often hinge on contested distinctions between exchange and exploitation.",
      "National identity, once treated as primordial, is now widely recognised as a historical construction.",
      "Diasporic identities frequently exist in productive tension with both ancestral and host cultures.",
      "Heritage preservation depends as much on community engagement as on institutional resources.",
      "Cosmopolitanism, in its more thoughtful versions, complements rather than dissolves particular attachments.",
      "Demographic change often outpaces the cultural narratives a society uses to interpret itself.",
      "Patronage and prestige hierarchies continue to shape which cultural products are deemed worthy of preservation.",
      "Soft power operates through cultural attractiveness rather than coercion, but is no less consequential.",
      "Generational shifts in values often reveal themselves through small linguistic changes before larger political ones.",
      "The aesthetics of authenticity can themselves become commodified within global cultural marketplaces.",
    ],
  },

  // ─── 14. government_politics ───
  {
    topic: "government_politics",
    level: "beginner",
    title: "Country and Government",
    description: "Rewrite simple sentences about national life and government.",
    sentences: [
      "Our country has a new president this year.",
      "Every citizen can vote when they are eighteen.",
      "The flag has three different colors.",
      "The parliament meets in the capital city.",
      "Students learn the national anthem at school.",
      "The mayor will visit our school next week.",
      "We have an election every five years.",
      "The new law starts next January.",
      "He works as a government employee.",
      "Citizens pay taxes to the government every year.",
    ],
  },
  {
    topic: "government_politics",
    level: "intermediate",
    title: "Politics and Public Policy",
    description:
      "Paraphrase sentences about political processes and civic life.",
    sentences: [
      "Voter turnout tends to be higher in elections that are perceived as truly competitive.",
      "Policymakers must often balance short-term political pressures against long-term national interests.",
      "Many democracies require political parties to disclose their major donors.",
      "Public protests have historically played a key role in shaping legislative agendas.",
      "Government budgets reveal what a country truly values, not just what it claims to.",
      "Many citizens feel disconnected from politicians they rarely see in person.",
      "Media coverage can significantly influence public perception of political candidates.",
      "Independent candidates often struggle to compete with major party machines.",
      "Local elections frequently determine matters closer to citizens' daily lives.",
      "Term limits aim to prevent the concentration of power in any single individual.",
      "Public-opinion polls have become a near-constant feature of modern political life.",
      "Lobbying remains controversial because of its potential to outweigh ordinary citizens' voices.",
    ],
  },
  {
    topic: "government_politics",
    level: "advanced",
    title: "Governance and Political Discourse",
    description:
      "Rephrase nuanced sentences about democracy, institutions, and policy.",
    sentences: [
      "The erosion of trust in democratic institutions is among the most consequential developments of recent decades.",
      "Populist rhetoric thrives in environments where citizens perceive elites as fundamentally unresponsive.",
      "Legislative gridlock often masks deeper structural impasses rather than mere partisan disagreement.",
      "Constitutional safeguards are only as effective as the political will required to uphold them.",
      "Foreign policy invariably reflects a delicate balance between principle and pragmatism.",
      "Electoral systems shape the kinds of coalitions that emerge in ways their designers may not have intended.",
      "Polarisation tends to feed on itself, with each side's escalation furnishing the other's justification.",
      "Democratic backsliding rarely takes the form of a single coup; it accumulates through small institutional concessions.",
      "Civil-society organisations function as the connective tissue between formal institutions and citizen experience.",
      "The professionalisation of politics has produced cohorts of operatives whose interests diverge from those of the electorate.",
      "Constitutional amendments are difficult by design, but that difficulty can entrench injustices as well as protect liberties.",
      "Geopolitical realignment often unfolds beneath the visible surface of formal diplomatic relations.",
      "Soft power and hard power, while analytically distinct, operate in mutually reinforcing combinations.",
      "The legitimacy of public institutions depends on procedural integrity at least as much as on substantive outcomes.",
      "Political discourse increasingly conflates disagreement on facts with disagreement on values, to the detriment of both.",
    ],
  },

  // ─── 15. history_geography ───
  {
    topic: "history_geography",
    level: "beginner",
    title: "History and Places",
    description: "Rewrite simple sentences about famous places and the past.",
    sentences: [
      "The pyramids of Egypt are very old.",
      "Vietnam is a country in Southeast Asia.",
      "My grandfather lived in this village many years ago.",
      "The Great Wall of China is many kilometres long.",
      "Paris is the capital of France.",
      "The Nile is the longest river in Africa.",
      "Tokyo has more than thirty million residents.",
      "There are many famous temples in Kyoto.",
      "He visited the museum of national history.",
      "Many people still live in old town centres.",
    ],
  },
  {
    topic: "history_geography",
    level: "intermediate",
    title: "World History and Geography",
    description:
      "Paraphrase sentences about historical events and geographic features.",
    sentences: [
      "The Silk Road connected ancient civilisations across Asia, Africa, and Europe.",
      "Mountain ranges often act as natural borders between countries.",
      "Many ancient temples have survived for centuries thanks to careful preservation.",
      "Migration has shaped the cultural and linguistic landscape of nearly every nation.",
      "World War II reshaped national borders across Europe and Asia.",
      "Coastal cities have historically been hubs of commerce and cultural exchange.",
      "The Industrial Revolution transformed not just economies but entire ways of life.",
      "Volcanic activity has shaped islands like Iceland and Hawaii over millennia.",
      "Many large cities were originally founded along major rivers.",
      "The Roman Empire left a lasting legacy on law and language across Europe.",
      "Climate has always played a significant role in shaping where civilisations flourished.",
      "Trade routes between Europe and Asia drove some of history's earliest globalisation.",
    ],
  },
  {
    topic: "history_geography",
    level: "advanced",
    title: "Historiography and Civilizations",
    description:
      "Rephrase complex sentences about historical analysis and geography.",
    sentences: [
      "Historiography is shaped as much by the prejudices of its writers as by the events it purports to chronicle.",
      "The collapse of empires rarely follows a single cause; it is typically the convergence of multiple stresses.",
      "Geographic determinism, though seductive, oversimplifies the manifold drivers of human development.",
      "Archaeological discoveries periodically force a reassessment of long-accepted historical narratives.",
      "Cartography has always doubled as an instrument of power as well as a tool of knowledge.",
      "The longue durée perspective foregrounds slow-moving structural changes that shorter timeframes obscure.",
      "Imperial decline often follows from peripheral overextension rather than core military defeat.",
      "Counterfactual history sharpens our understanding of causation by isolating decisive turning points.",
      "Oral traditions preserve forms of knowledge that written records frequently fail to capture.",
      "Border disputes draw on historical claims that frequently obscure as much as they reveal.",
      "The mapping of the world has historically reflected European epistemological assumptions even where it pretended to objectivity.",
      "Subaltern history attempts to recover voices systematically excluded from dominant narratives.",
      "Migrations leave linguistic fingerprints that endure long after the populations themselves have dispersed.",
      "Climate fluctuations have been credibly linked to the rise and fall of agricultural civilisations.",
      "The discipline of history straddles the boundary between humanities and social science in productively uncomfortable ways.",
    ],
  },

  // ─── 16. sports_fitness ───
  {
    topic: "sports_fitness",
    level: "beginner",
    title: "Playing Sports",
    description: "Rewrite simple sentences about sports and exercise.",
    sentences: [
      "He plays football every weekend.",
      "I run in the park every morning.",
      "Swimming is good for your health.",
      "She is a member of the school basketball team.",
      "We watched the badminton match on television.",
      "My friend joined a yoga class last month.",
      "The marathon takes place every spring.",
      "He won the first prize at the chess tournament.",
      "Skating is dangerous without proper protection.",
      "I always stretch before exercising.",
    ],
  },
  {
    topic: "sports_fitness",
    level: "intermediate",
    title: "Fitness and Athletic Performance",
    description:
      "Paraphrase sentences about training, sports, and personal fitness.",
    sentences: [
      "Strength training is just as important as cardio for overall fitness.",
      "Professional athletes follow strict diets to maintain their performance levels.",
      "Joining a sports club is a great way to stay motivated and meet new people.",
      "Rest days are essential to allow muscles to recover and grow stronger.",
      "Many people prefer team sports because of the social aspect.",
      "Wearable fitness trackers have changed how people monitor their workouts.",
      "Hydration is critical, especially during long endurance events.",
      "Cross-training helps prevent the kinds of injuries caused by overuse.",
      "Most beginners progress faster when working with a qualified coach.",
      "Outdoor running offers benefits that treadmills can never quite replicate.",
      "Stretching after exercise reduces stiffness the following day.",
      "Many gyms now offer free trial periods to encourage new members.",
    ],
  },
  {
    topic: "sports_fitness",
    level: "advanced",
    title: "Sports Science and Elite Performance",
    description:
      "Rephrase nuanced sentences about athletic performance and sports culture.",
    sentences: [
      "Marginal gains in elite athletics often hinge on imperceptible refinements to technique and recovery.",
      "The commercialisation of professional sport has reshaped both fan engagement and athlete compensation.",
      "Sports psychology has emerged as a decisive factor in performance under pressure.",
      "Overtraining syndrome demonstrates that more effort does not invariably yield better outcomes.",
      "Doping controversies continue to expose the fault lines between competitive integrity and athletic ambition.",
      "Periodisation in training reflects a sophisticated understanding of physiological adaptation cycles.",
      "Sports analytics has reshaped tactical decision-making in ways that purists initially resisted.",
      "The biomechanics of elite performance often defy intuition built on everyday human movement.",
      "Talent identification remains an imperfect science prone to both false positives and missed prodigies.",
      "The transition from elite athletics to civilian life presents psychological challenges still underappreciated.",
      "Concussion research has belatedly forced rule changes across contact sports.",
      "Women's sport has historically suffered from systematic under-investment despite comparable competitive merit.",
      "The home advantage in elite competition encompasses far more than crowd support alone.",
      "Sponsorship has become inseparable from elite competition, blurring sport and marketing in complex ways.",
      "Recovery science has expanded from sleep and nutrition to include genetic and microbiome considerations.",
    ],
  },

  // ─── 17. arts_literature ───
  {
    topic: "arts_literature",
    level: "beginner",
    title: "Books and Art",
    description: "Rewrite simple sentences about reading and art.",
    sentences: [
      "I love reading children's books.",
      "She drew a picture of a cat.",
      "We visited a museum last weekend.",
      "He wrote a poem for his mother.",
      "The painting on the wall is very colourful.",
      "She practices the piano every afternoon.",
      "I borrowed three novels from the library.",
      "He likes to draw cartoons in his notebook.",
      "Many bookshops sell coffee as well.",
      "She often takes photos at the local park.",
    ],
  },
  {
    topic: "arts_literature",
    level: "intermediate",
    title: "Literature and the Visual Arts",
    description:
      "Paraphrase sentences about reading, painting, and creative expression.",
    sentences: [
      "Reading novels can broaden your perspective by exposing you to different ways of thinking.",
      "Many famous painters were not appreciated until long after their deaths.",
      "Poetry often communicates emotions that ordinary prose struggles to express.",
      "Modern art frequently invites the viewer to participate in completing its meaning.",
      "Many writers keep daily journals to capture stray ideas and impressions.",
      "Book clubs continue to thrive despite the dominance of digital entertainment.",
      "Photography has become both an accessible hobby and a fine-art tradition.",
      "Theatre productions can interpret classic plays in surprisingly contemporary ways.",
      "Independent bookshops often host readings that build community around literature.",
      "Graphic novels have earned literary recognition once reserved for traditional prose.",
      "Many art exhibitions now combine paintings with multimedia installations.",
      "Cover design plays a surprisingly large role in whether a book gets picked up.",
    ],
  },
  {
    topic: "arts_literature",
    level: "advanced",
    title: "Aesthetics and Literary Theory",
    description:
      "Rephrase complex sentences about art criticism and literary analysis.",
    sentences: [
      "Literary modernism eschewed linear narrative in favour of fragmented forms that mirror the dislocations of modern consciousness.",
      "The valuation of contemporary art is shaped as much by institutional gatekeepers as by aesthetic merit.",
      "Translation is less an act of equivalence than a creative negotiation between two linguistic worlds.",
      "Aesthetic judgments, while often presented as universal, betray the cultural moments that produced them.",
      "Postmodern literature destabilises the very conventions it ostensibly employs.",
      "The canon, as traditionally constituted, reflects historical hierarchies as much as artistic excellence.",
      "Art criticism mediates between specialised practice and public understanding, often imperfectly.",
      "Narratology has revealed the structural commonalities underlying superficially diverse storytelling traditions.",
      "Avant-garde movements gain meaning largely through their negation of the orthodoxies they oppose.",
      "The materiality of the book — paper, binding, weight — shapes reading in ways e-readers rarely replicate.",
      "Mimesis and abstraction represent enduring polarities through which visual art continually redefines itself.",
      "Literary reputations frequently undergo dramatic revisions across generations of critical reception.",
      "Genre fiction has belatedly been recognised as a legitimate site of serious literary inquiry.",
      "Curation is itself a creative act, framing artworks in ways that condition their reception.",
      "The relationship between artist and audience is mediated by institutional infrastructures rarely visible in the finished work.",
    ],
  },

  // ─── 18. religion_spirituality ───
  {
    topic: "religion_spirituality",
    level: "beginner",
    title: "Religion and Belief",
    description: "Rewrite simple sentences about temples, prayers, and belief.",
    sentences: [
      "My grandmother goes to the pagoda every full moon.",
      "He prays before he eats dinner.",
      "Many people believe in their family ancestors.",
      "The temple is very quiet in the early morning.",
      "She lights incense at the family altar daily.",
      "The monks live in the old monastery in the hills.",
      "We light candles on the religious holiday.",
      "My uncle reads from a holy book every evening.",
      "The church bells ring on Sunday morning.",
      "Many tourists visit the famous pagoda each year.",
    ],
  },
  {
    topic: "religion_spirituality",
    level: "intermediate",
    title: "Faith and Spiritual Practice",
    description:
      "Paraphrase sentences about religion, meditation, and spirituality.",
    sentences: [
      "Meditation is increasingly recommended by doctors as a tool for managing anxiety.",
      "Religious holidays often bring families together more than ordinary weekends.",
      "Many monasteries open their doors to visitors who want a temporary escape from daily life.",
      "Spirituality and religion are not always the same thing for everyone.",
      "Mindfulness practices have spread widely beyond their traditional religious roots.",
      "Interfaith dialogue can be a powerful tool for community cohesion.",
      "Many young people define themselves as spiritual without belonging to any organised religion.",
      "Religious texts continue to inspire literature, music, and art across cultures.",
      "Pilgrimage remains an important practice in many faith traditions today.",
      "Faith-based charities deliver crucial services in many under-served regions.",
      "Daily rituals can foster a sense of meaning regardless of one's broader beliefs.",
      "Religious dietary practices often reflect deep historical and cultural significance.",
    ],
  },
  {
    topic: "religion_spirituality",
    level: "advanced",
    title: "Theology and Religious Pluralism",
    description:
      "Rephrase complex sentences about religion, ethics, and pluralism.",
    sentences: [
      "Religious pluralism demands not merely tolerance but a genuine willingness to engage with unfamiliar worldviews.",
      "Secularisation has not so much eliminated belief as redistributed it across new forms of identity.",
      "Mystical traditions across cultures share remarkable structural parallels despite differing doctrines.",
      "Sacred texts inevitably accumulate layers of interpretation that complicate any claim to literal meaning.",
      "The relationship between organised religion and political power has rarely been comfortable for either party.",
      "Apophatic theology approaches the divine through what it is not rather than what it is.",
      "Comparative religion reveals both the universality of certain themes and the irreducibility of particular practices.",
      "Liturgical traditions encode theological commitments through patterns of repetition and embodiment.",
      "Religious modernism has wrestled with how to remain doctrinally coherent while engaging contemporary thought.",
      "Fundamentalism, paradoxically, is a distinctly modern phenomenon shaped by the conditions it claims to resist.",
      "The phenomenology of religious experience resists reduction to either neurology or pure social construction.",
      "Sacred space functions both architecturally and psychologically to mediate the transcendent.",
      "Religious authority traditions struggle with how to incorporate dissent without forfeiting coherence.",
      "Spiritual but not religious self-identification reflects both individualism and continued hunger for meaning.",
      "Eschatological frameworks shape how religious communities relate to political and ecological crises.",
    ],
  },

  // ─── 19. law_justice ───
  {
    topic: "law_justice",
    level: "beginner",
    title: "Rules and Police",
    description: "Rewrite simple sentences about laws and the police.",
    sentences: [
      "We must follow the traffic rules.",
      "The police help people who are in trouble.",
      "She told the truth in court.",
      "The judge listened carefully to both sides.",
      "He paid a fine for parking incorrectly.",
      "Children should not play in dangerous places.",
      "It is illegal to drive without a licence.",
      "She reported the lost wallet to the police.",
      "The lawyer asked many questions in court.",
      "Many countries have different laws.",
    ],
  },
  {
    topic: "law_justice",
    level: "intermediate",
    title: "Law and Justice in Daily Life",
    description:
      "Paraphrase sentences about everyday legal matters and justice.",
    sentences: [
      "Hiring a lawyer is often necessary when dealing with complex legal disputes.",
      "Many countries have introduced stricter penalties for drunk driving in recent years.",
      "Jury duty is considered an important civic responsibility in many democracies.",
      "Reading a contract carefully before signing can save you considerable trouble later.",
      "Consumer protection laws aim to keep the marketplace fair for ordinary buyers.",
      "Police presence on city streets affects both real and perceived safety.",
      "Civil cases generally focus on disputes between private parties rather than crimes.",
      "Small-claims courts are designed to handle simpler disputes quickly.",
      "Tenants often have legal protections that landlords are required to respect.",
      "Workplace harassment laws have become much more rigorously enforced.",
      "Cybercrime presents new challenges that traditional legal frameworks struggle to address.",
      "Court records are usually available to the public, except in sensitive cases.",
    ],
  },
  {
    topic: "law_justice",
    level: "advanced",
    title: "Jurisprudence and the Rule of Law",
    description:
      "Rephrase nuanced sentences about legal philosophy and judicial systems.",
    sentences: [
      "The rule of law presupposes that no individual, however powerful, stands above its provisions.",
      "Judicial activism, while occasionally necessary, risks blurring the boundaries between adjudication and legislation.",
      "Restorative justice frameworks seek to repair harm rather than merely allocate punishment.",
      "Constitutional interpretation involves balancing textual fidelity against evolving social realities.",
      "Access to legal representation remains a persistent disparity in even the most developed legal systems.",
      "Procedural fairness sometimes diverges from substantive justice in ways the law has yet to reconcile.",
      "International law operates under structural constraints that domestic systems rarely encounter.",
      "Plea bargaining, while efficient, raises serious questions about voluntariness under duress.",
      "Sentencing disparities expose biases that purport-to-be-neutral guidelines often fail to eliminate.",
      "The presumption of innocence is foundational, yet operates in tension with media pre-trial coverage.",
      "Legal pluralism recognises that multiple normative orders may coexist within a single jurisdiction.",
      "The doctrine of stare decisis stabilises law but can entrench past mistakes if not periodically reconsidered.",
      "Administrative law has expanded to govern domains the framers of older constitutions could not have foreseen.",
      "The interpretation of human rights has evolved through dialogue between national and supranational courts.",
      "Legal positivism and natural-law traditions continue to wrestle over whether morality is intrinsic to law.",
    ],
  },

  // ─── 20. philosophy_ethics ───
  {
    topic: "philosophy_ethics",
    level: "beginner",
    title: "Right and Wrong",
    description: "Rewrite simple sentences about ideas of right and wrong.",
    sentences: [
      "It is important to be honest.",
      "We should help people in need.",
      "Stealing is wrong.",
      "Telling the truth is always better than lying.",
      "We should not cheat in school exams.",
      "He apologised for being rude.",
      "She always treats animals with kindness.",
      "Sharing is a good habit to learn.",
      "We must respect older people.",
      "Children should listen to their parents.",
    ],
  },
  {
    topic: "philosophy_ethics",
    level: "intermediate",
    title: "Ethics and Moral Choices",
    description:
      "Paraphrase sentences about ethical dilemmas and personal values.",
    sentences: [
      "Telling a small lie to protect someone's feelings raises difficult moral questions.",
      "Some philosophers argue that the consequences of an action matter more than the intentions behind it.",
      "Many people struggle to balance personal happiness with their responsibilities to others.",
      "Ethical behaviour in business is often tested when profits and principles come into conflict.",
      "Volunteering is widely considered a meaningful way to contribute to one's community.",
      "Treating strangers with kindness can have ripple effects far beyond the original gesture.",
      "Many cultures share similar core values despite very different religious traditions.",
      "Personal integrity is often most clearly revealed in situations of no external pressure.",
      "Many ethical frameworks emphasise that means and ends both deserve careful evaluation.",
      "Online behaviour now raises moral questions that earlier generations rarely had to consider.",
      "Forgiveness, while difficult, is often described as essential to long-term well-being.",
      "Moral courage is the willingness to do the right thing even when it is socially costly.",
    ],
  },
  {
    topic: "philosophy_ethics",
    level: "advanced",
    title: "Moral Philosophy and Existential Inquiry",
    description:
      "Rephrase complex sentences about ethics, meaning, and human existence.",
    sentences: [
      "Consequentialist ethics evaluate actions by their outcomes, often at the cost of overlooking the intrinsic morality of means.",
      "Existentialism insists that meaning is not discovered but actively constructed through deliberate choice.",
      "Moral relativism challenges the possibility of cross-cultural ethical evaluation without dismissing it outright.",
      "Virtue ethics shifts the focus from isolated decisions to the cultivation of enduring character traits.",
      "The trolley problem, however contrived, remains a remarkably revealing probe of our moral intuitions.",
      "Deontological reasoning maintains that certain actions are intrinsically wrong regardless of their consequences.",
      "Phenomenology brackets metaphysical assumptions to examine the structure of experience itself.",
      "The hard problem of consciousness resists reduction to neuroscience or computational analogy alone.",
      "Stoicism enjoys renewed contemporary appeal precisely because of its practical psychological orientation.",
      "Free will and moral responsibility remain entangled in ways that empirical findings have not resolved.",
      "Utilitarianism, despite its elegance, faces persistent objections regarding the aggregation of interpersonal welfare.",
      "Care ethics centres relational obligations that more abstract frameworks have historically marginalised.",
      "The is-ought distinction continues to vex any attempt to derive moral imperatives from descriptive facts.",
      "Cosmopolitan ethics challenges the moral primacy traditionally accorded to compatriots over strangers.",
      "Moral progress, often invoked rhetorically, proves remarkably difficult to define without circular reasoning.",
    ],
  },
];

function buildBody(entry) {
  return {
    title: entry.title,
    level: entry.level,
    topic: entry.topic,
    description: entry.description,
    sentences: entry.sentences.map((s) => ({ targetSentence: s })),
  };
}

async function run() {
  await CONNECT_DB();
  console.log(
    `Mode: ${FORCE ? "FORCE (allow duplicate titles)" : "DEDUPE by title"}`,
  );
  console.log(`Planning ${LESSONS.length} lessons.\n`);

  let created = 0;
  let skipped = 0;
  let failed = 0;

  for (const entry of LESSONS) {
    try {
      if (!FORCE) {
        const exists = await Rewrite.exists({ title: entry.title });
        if (exists) {
          skipped++;
          console.log(`SKIP  [${entry.level}] ${entry.title}`);
          continue;
        }
      }
      const lesson = await createLesson(buildBody(entry));
      created++;
      console.log(
        `OK    [${entry.level}] ${entry.title} (${entry.sentences.length} câu) → ${lesson._id}`,
      );
    } catch (err) {
      failed++;
      console.error(`FAIL  ${entry.title}: ${err.message}`);
    }
  }

  console.log(
    `\nSummary: created=${created}, skipped=${skipped}, failed=${failed}`,
  );
  await mongoose.disconnect();
}

run().catch((e) => {
  console.error(e);
  process.exit(1);
});
