import "dotenv/config";
import mongoose from "mongoose";
import { CONNECT_DB } from "@server/config/mongodb";
import { Exam } from "@server/models/writing/Exam";
import { createExam } from "@server/services/examService";

/**
 * Seed 60 IELTS Exam simulations: 20 topics × 3 levels.
 * Distribution:
 *   - beginner    → ielts_task1 (describe a chart/diagram; imageUrl required)
 *   - intermediate → ielts_task2 (opinion essay)
 *   - advanced    → ielts_task2 (discuss both views / problem-solution)
 *
 * Follows the real admin flow (examService.createExam → createWriting → prepareExam).
 *
 * Idempotent: skip if an exam with the same title already exists (unless FORCE=1).
 *
 * Usage:
 *   pnpm dlx @babel/node src/commands/seedExam.js
 *   FORCE=1 pnpm dlx @babel/node src/commands/seedExam.js
 *
 * UPDATE_IMAGES=1: instead of creating, only update `imageUrl` on existing
 * exams matched by title. Use this to patch already-seeded task1 exams whose
 * images were generated by an older version of this script.
 */

const FORCE = process.env.FORCE === "1";
const UPDATE_IMAGES = process.env.UPDATE_IMAGES === "1";

/**
 * Generate a chart image URL via quickchart.io from a Chart.js config object.
 * Used for IELTS Task 1 prompts so the image actually matches the data the
 * student is asked to describe (otherwise AI grading is meaningless).
 */
function chartUrl(config) {
  const params = new URLSearchParams({
    width: "900",
    height: "560",
    backgroundColor: "white",
    c: JSON.stringify(config),
  });
  return `https://quickchart.io/chart?${params}`;
}

const COLORS = ["#4F46E5", "#10B981", "#F59E0B", "#EF4444", "#8B5CF6", "#06B6D4"];

const EXAMS = [
  // ─── 1. personal_communication ───
  {
    topic: "personal_communication",
    level: "beginner",
    examType: "ielts_task1",
    title: "Bar Chart: Mobile vs. In-Person Communication",
    description: "Describe how people of different ages prefer to communicate.",
    examPrompt: "The bar chart below shows the preferred communication methods (in-person, phone call, text message, video call) of four age groups in a European country in 2024. Summarise the information by selecting and reporting the main features, and make comparisons where relevant. Write at least 150 words.",
    imageUrl: chartUrl({
      type: "bar",
      data: {
        labels: ["18-29", "30-49", "50-64", "65+"],
        datasets: [
          { label: "In-person", data: [22, 30, 48, 68], backgroundColor: COLORS[0] },
          { label: "Phone call", data: [12, 24, 32, 26], backgroundColor: COLORS[1] },
          { label: "Text message", data: [50, 32, 16, 5], backgroundColor: COLORS[2] },
          { label: "Video call", data: [16, 14, 4, 1], backgroundColor: COLORS[3] },
        ],
      },
      options: {
        title: { display: true, text: "Preferred Communication Methods by Age Group (2024, %)" },
        scales: { yAxes: [{ ticks: { beginAtZero: true, max: 80 } }] },
      },
    }),
  },
  {
    topic: "personal_communication",
    level: "intermediate",
    examType: "ielts_task2",
    title: "Essay: Social Media Replacing Face-to-Face Contact",
    description: "Discuss whether social media is harming personal relationships.",
    examPrompt: "Some people believe that social media platforms have replaced traditional face-to-face communication, especially among young people. Do you think this trend is mostly positive or mostly negative? Give reasons for your answer and include any relevant examples from your own knowledge or experience. Write at least 250 words.",
  },
  {
    topic: "personal_communication",
    level: "advanced",
    examType: "ielts_task2",
    title: "Essay: The Erosion of Deep Conversation in Digital Age",
    description: "Argue both sides on the decline of meaningful conversation.",
    examPrompt: "Some commentators argue that constant digital connectivity has eroded our capacity for deep, sustained conversation, while others maintain that technology has merely changed — not diminished — how meaningful dialogue takes place. Discuss both views and give your own opinion. Write at least 250 words.",
  },

  // ─── 2. everyday_life ───
  {
    topic: "everyday_life",
    level: "beginner",
    examType: "ielts_task1",
    title: "Pie Chart: Time Spent on Daily Activities",
    description: "Describe how an average adult spends their day.",
    examPrompt: "The pie chart below shows the proportion of a typical weekday spent on different activities (work, sleep, eating, leisure, household chores, commuting) by an average adult in 2024. Summarise the information by selecting and reporting the main features, and make comparisons where relevant. Write at least 150 words.",
    imageUrl: chartUrl({
      type: "pie",
      data: {
        labels: ["Work", "Sleep", "Leisure", "Household chores", "Commuting", "Eating"],
        datasets: [
          {
            data: [33, 32, 12, 10, 7, 6],
            backgroundColor: COLORS,
          },
        ],
      },
      options: {
        title: { display: true, text: "Time Spent on Daily Activities (Weekday, %)" },
      },
    }),
  },
  {
    topic: "everyday_life",
    level: "intermediate",
    examType: "ielts_task2",
    title: "Essay: Work-Life Balance in Modern Cities",
    description: "Discuss whether modern lifestyles allow time for personal life.",
    examPrompt: "Many people today find it hard to balance demanding jobs with family and personal life. What are the main reasons for this, and what can individuals or governments do to improve the situation? Write at least 250 words.",
  },
  {
    topic: "everyday_life",
    level: "advanced",
    examType: "ielts_task2",
    title: "Essay: Slow Living vs. Productivity Culture",
    description: "Argue both views on slow living versus hyper-productivity.",
    examPrompt: "Some argue that the modern emphasis on productivity has made everyday life joyless, advocating for a 'slow living' philosophy, while others insist that productivity remains the surest path to personal and economic well-being. Discuss both views and give your own opinion. Write at least 250 words.",
  },

  // ─── 3. transportation_travel ───
  {
    topic: "transportation_travel",
    level: "beginner",
    examType: "ielts_task1",
    title: "Line Chart: Daily Train Passengers in 5 Cities",
    description: "Describe daily train ridership trends.",
    examPrompt: "The line chart below shows the average number of daily train passengers (in thousands) in five major cities between 2010 and 2024. Summarise the information by selecting and reporting the main features, and make comparisons where relevant. Write at least 150 words.",
    imageUrl: chartUrl({
      type: "line",
      data: {
        labels: ["2010", "2012", "2014", "2016", "2018", "2020", "2022", "2024"],
        datasets: [
          { label: "Tokyo", data: [2400, 2480, 2550, 2620, 2700, 1800, 2350, 2620], borderColor: COLORS[0], fill: false },
          { label: "Paris", data: [1500, 1530, 1560, 1600, 1640, 1100, 1480, 1620], borderColor: COLORS[1], fill: false },
          { label: "London", data: [1200, 1240, 1280, 1320, 1370, 800, 1180, 1340], borderColor: COLORS[2], fill: false },
          { label: "Seoul", data: [1800, 1860, 1920, 1980, 2050, 1400, 1800, 2030], borderColor: COLORS[3], fill: false },
          { label: "Berlin", data: [900, 920, 950, 980, 1010, 700, 920, 1020], borderColor: COLORS[4], fill: false },
        ],
      },
      options: {
        title: { display: true, text: "Average Daily Train Passengers (thousands), 2010-2024" },
      },
    }),
  },
  {
    topic: "transportation_travel",
    level: "intermediate",
    examType: "ielts_task2",
    title: "Essay: Should Cities Restrict Private Cars?",
    description: "Argue for or against restricting private cars in city centers.",
    examPrompt: "Some city governments are introducing strict measures to limit the use of private cars in urban areas. Do the advantages of such policies outweigh the disadvantages? Give reasons for your answer with relevant examples. Write at least 250 words.",
  },
  {
    topic: "transportation_travel",
    level: "advanced",
    examType: "ielts_task2",
    title: "Essay: The Future of Aviation and Climate",
    description: "Discuss the tension between aviation growth and climate goals.",
    examPrompt: "Demand for international air travel continues to rise, even as governments commit to ambitious carbon-reduction targets. To what extent is it possible to reconcile these competing pressures, and what role, if any, should individual travelers play? Write at least 250 words.",
  },

  // ─── 4. school_education ───
  {
    topic: "school_education",
    level: "beginner",
    examType: "ielts_task1",
    title: "Bar Chart: Subjects Chosen by High School Students",
    description: "Describe popular subject choices among high schoolers.",
    examPrompt: "The bar chart below shows the percentage of high school students choosing various optional subjects (Maths, Science, Languages, Arts, Computing, Music) in 2014 and 2024. Summarise the information by selecting and reporting the main features, and make comparisons where relevant. Write at least 150 words.",
    imageUrl: chartUrl({
      type: "bar",
      data: {
        labels: ["Maths", "Science", "Languages", "Arts", "Computing", "Music"],
        datasets: [
          { label: "2014", data: [55, 48, 40, 28, 18, 14], backgroundColor: COLORS[0] },
          { label: "2024", data: [58, 52, 32, 22, 42, 10], backgroundColor: COLORS[2] },
        ],
      },
      options: {
        title: { display: true, text: "Optional Subjects Chosen by High School Students (%)" },
      },
    }),
  },
  {
    topic: "school_education",
    level: "intermediate",
    examType: "ielts_task2",
    title: "Essay: Online Learning vs. Traditional Classrooms",
    description: "Discuss the rise of online learning.",
    examPrompt: "Online learning has become widely available, with many universities now offering full degrees over the internet. Do you think online education will eventually replace traditional classroom-based learning? Give reasons for your answer. Write at least 250 words.",
  },
  {
    topic: "school_education",
    level: "advanced",
    examType: "ielts_task2",
    title: "Essay: Standardized Testing in Higher Education",
    description: "Argue both views on standardized university admissions tests.",
    examPrompt: "Standardized admissions tests have come under increasing criticism for failing to capture the full breadth of student potential, while others argue that without such tests, university admissions would become entirely subjective. Discuss both views and give your own opinion. Write at least 250 words.",
  },

  // ─── 5. work_business ───
  {
    topic: "work_business",
    level: "beginner",
    examType: "ielts_task1",
    title: "Bar Chart: Remote Work Adoption by Industry",
    description: "Describe remote-work rates across industries.",
    examPrompt: "The bar chart below shows the percentage of employees working remotely in six industries (Technology, Finance, Education, Retail, Manufacturing, Healthcare) in 2019 and 2024. Summarise the information by selecting and reporting the main features, and make comparisons where relevant. Write at least 150 words.",
    imageUrl: chartUrl({
      type: "bar",
      data: {
        labels: ["Technology", "Finance", "Education", "Retail", "Manufacturing", "Healthcare"],
        datasets: [
          { label: "2019", data: [22, 8, 4, 3, 2, 5], backgroundColor: COLORS[0] },
          { label: "2024", data: [68, 45, 32, 12, 6, 18], backgroundColor: COLORS[2] },
        ],
      },
      options: {
        title: { display: true, text: "Employees Working Remotely by Industry (%)" },
      },
    }),
  },
  {
    topic: "work_business",
    level: "intermediate",
    examType: "ielts_task2",
    title: "Essay: Four-Day Work Week",
    description: "Discuss whether a four-day work week should be standard.",
    examPrompt: "Some companies have started offering a four-day work week to their employees. Do the benefits of this shorter schedule outweigh the potential drawbacks for both employers and workers? Give reasons for your answer and include any relevant examples. Write at least 250 words.",
  },
  {
    topic: "work_business",
    level: "advanced",
    examType: "ielts_task2",
    title: "Essay: Automation and the Future of Employment",
    description: "Argue both views on automation's impact on jobs.",
    examPrompt: "Some economists predict that increasing automation will eliminate vast numbers of jobs and require radical changes to social safety nets, while others contend that history shows new technologies invariably create more jobs than they destroy. Discuss both views and give your own opinion. Write at least 250 words.",
  },

  // ─── 6. public_services ───
  {
    topic: "public_services",
    level: "beginner",
    examType: "ielts_task1",
    title: "Bar Chart: Public Library Visits by Age Group",
    description: "Describe library visits across age groups.",
    examPrompt: "The bar chart below shows the average number of public library visits per year by four age groups in two cities (City A and City B) in 2024. Summarise the information by selecting and reporting the main features, and make comparisons where relevant. Write at least 150 words.",
    imageUrl: chartUrl({
      type: "bar",
      data: {
        labels: ["Under 18", "18-30", "31-55", "Over 55"],
        datasets: [
          { label: "City A", data: [14, 8, 5, 18], backgroundColor: COLORS[0] },
          { label: "City B", data: [9, 12, 7, 22], backgroundColor: COLORS[2] },
        ],
      },
      options: {
        title: { display: true, text: "Public Library Visits per Year by Age Group (2024)" },
      },
    }),
  },
  {
    topic: "public_services",
    level: "intermediate",
    examType: "ielts_task2",
    title: "Essay: Digital Government Services",
    description: "Discuss the shift to digital public services.",
    examPrompt: "Many governments are moving essential public services entirely online, such as tax filing, healthcare appointments, and vehicle registration. Do the advantages of digital public services outweigh the disadvantages, especially for older or less tech-savvy citizens? Write at least 250 words.",
  },
  {
    topic: "public_services",
    level: "advanced",
    examType: "ielts_task2",
    title: "Essay: Privatization of Essential Public Services",
    description: "Argue both views on privatizing utilities and transport.",
    examPrompt: "Some governments have privatized essential public services such as water, transport, and electricity, arguing that competition improves efficiency. Others maintain that such services are too critical to leave to market forces. Discuss both views and give your own opinion. Write at least 250 words.",
  },

  // ─── 7. health_medicine ───
  {
    topic: "health_medicine",
    level: "beginner",
    examType: "ielts_task1",
    title: "Line Chart: Average Life Expectancy in Four Countries",
    description: "Describe life expectancy changes over time.",
    examPrompt: "The line chart below shows the average life expectancy at birth (in years) in four countries between 1950 and 2020. Summarise the information by selecting and reporting the main features, and make comparisons where relevant. Write at least 150 words.",
    imageUrl: chartUrl({
      type: "line",
      data: {
        labels: ["1950", "1960", "1970", "1980", "1990", "2000", "2010", "2020"],
        datasets: [
          { label: "Japan", data: [60, 68, 73, 76, 79, 81, 83, 84], borderColor: COLORS[0], fill: false },
          { label: "USA", data: [68, 70, 71, 74, 75, 77, 78, 79], borderColor: COLORS[1], fill: false },
          { label: "Brazil", data: [51, 56, 60, 64, 68, 71, 74, 76], borderColor: COLORS[2], fill: false },
          { label: "India", data: [37, 43, 49, 55, 60, 64, 67, 70], borderColor: COLORS[3], fill: false },
        ],
      },
      options: {
        title: { display: true, text: "Average Life Expectancy at Birth (years), 1950-2020" },
      },
    }),
  },
  {
    topic: "health_medicine",
    level: "intermediate",
    examType: "ielts_task2",
    title: "Essay: Should Junk Food Be Taxed?",
    description: "Discuss whether governments should tax unhealthy foods.",
    examPrompt: "Some governments are considering imposing higher taxes on foods and drinks that are high in sugar, salt, or fat. Do you think this policy is an effective way to improve public health? Give reasons for your answer with relevant examples. Write at least 250 words.",
  },
  {
    topic: "health_medicine",
    level: "advanced",
    examType: "ielts_task2",
    title: "Essay: Public vs. Private Healthcare Systems",
    description: "Argue both views on universal healthcare.",
    examPrompt: "Some argue that universal public healthcare is the only ethical model for a modern society, while others contend that private healthcare drives faster innovation and better outcomes for those who can afford it. Discuss both views and give your own opinion. Write at least 250 words.",
  },

  // ─── 8. shopping_money ───
  {
    topic: "shopping_money",
    level: "beginner",
    examType: "ielts_task1",
    title: "Bar Chart: Online vs. In-Store Shopping",
    description: "Describe shopping channel preferences.",
    examPrompt: "The bar chart below shows the percentage of consumers who prefer online versus in-store shopping for five product categories (Clothing, Electronics, Groceries, Books, Furniture) in 2024. Summarise the information by selecting and reporting the main features, and make comparisons where relevant. Write at least 150 words.",
    imageUrl: chartUrl({
      type: "bar",
      data: {
        labels: ["Clothing", "Electronics", "Groceries", "Books", "Furniture"],
        datasets: [
          { label: "Online", data: [55, 72, 28, 65, 38], backgroundColor: COLORS[0] },
          { label: "In-store", data: [45, 28, 72, 35, 62], backgroundColor: COLORS[2] },
        ],
      },
      options: {
        title: { display: true, text: "Online vs. In-Store Shopping Preference (%, 2024)" },
      },
    }),
  },
  {
    topic: "shopping_money",
    level: "intermediate",
    examType: "ielts_task2",
    title: "Essay: Consumerism and Personal Finance",
    description: "Discuss the impact of consumer culture on saving.",
    examPrompt: "In many countries, household debt has risen sharply alongside increasing consumer spending. What are the main causes of this trend, and what can individuals do to manage their personal finances more responsibly? Write at least 250 words.",
  },
  {
    topic: "shopping_money",
    level: "advanced",
    examType: "ielts_task2",
    title: "Essay: The Death of Physical Retail",
    description: "Argue both views on the decline of physical stores.",
    examPrompt: "Some commentators predict that physical retail stores will largely disappear within a generation due to the rise of e-commerce, while others argue that brick-and-mortar shops will continue to serve essential social and experiential functions. Discuss both views and give your own opinion. Write at least 250 words.",
  },

  // ─── 9. food_drink ───
  {
    topic: "food_drink",
    level: "beginner",
    examType: "ielts_task1",
    title: "Pie Chart: Daily Calorie Sources for an Average Adult",
    description: "Describe calorie sources in the average diet.",
    examPrompt: "The pie chart below shows the proportion of daily calories obtained from different food groups (Grains, Vegetables & Fruit, Dairy, Meat & Fish, Sugars, Fats) for an average adult in a Western country in 2024. Summarise the information by selecting and reporting the main features, and make comparisons where relevant. Write at least 150 words.",
    imageUrl: chartUrl({
      type: "pie",
      data: {
        labels: ["Grains", "Vegetables & Fruit", "Meat & Fish", "Dairy", "Sugars", "Fats"],
        datasets: [
          {
            data: [30, 18, 22, 12, 11, 7],
            backgroundColor: COLORS,
          },
        ],
      },
      options: {
        title: { display: true, text: "Daily Calorie Sources for an Average Adult (%)" },
      },
    }),
  },
  {
    topic: "food_drink",
    level: "intermediate",
    examType: "ielts_task2",
    title: "Essay: Plant-Based Diets",
    description: "Discuss the rise of plant-based eating.",
    examPrompt: "An increasing number of people in developed countries are switching to plant-based diets for health, ethical, or environmental reasons. Do you think governments should encourage this trend, or should personal dietary choices remain entirely private? Write at least 250 words.",
  },
  {
    topic: "food_drink",
    level: "advanced",
    examType: "ielts_task2",
    title: "Essay: Globalization of Cuisine",
    description: "Argue both views on cuisine globalization.",
    examPrompt: "Some argue that the global spread of food trends has enriched local cuisines, while others contend that it has eroded traditional culinary practices and homogenized taste worldwide. Discuss both views and give your own opinion. Write at least 250 words.",
  },

  // ─── 10. entertainment_leisure ───
  {
    topic: "entertainment_leisure",
    level: "beginner",
    examType: "ielts_task1",
    title: "Bar Chart: Hours Spent on Leisure Activities Per Week",
    description: "Describe weekly leisure-time allocation.",
    examPrompt: "The bar chart below shows the average number of hours per week spent on five leisure activities (Watching TV, Gaming, Reading, Outdoor Sports, Social Outings) by two age groups (18-30 and 50-65) in 2024. Summarise the information by selecting and reporting the main features, and make comparisons where relevant. Write at least 150 words.",
    imageUrl: chartUrl({
      type: "bar",
      data: {
        labels: ["Watching TV", "Gaming", "Reading", "Outdoor Sports", "Social Outings"],
        datasets: [
          { label: "18-30", data: [9, 12, 3, 6, 8], backgroundColor: COLORS[0] },
          { label: "50-65", data: [16, 2, 7, 4, 5], backgroundColor: COLORS[2] },
        ],
      },
      options: {
        title: { display: true, text: "Hours per Week Spent on Leisure Activities (2024)" },
      },
    }),
  },
  {
    topic: "entertainment_leisure",
    level: "intermediate",
    examType: "ielts_task2",
    title: "Essay: Video Games — Hobby or Harm?",
    description: "Discuss the impact of video games on young people.",
    examPrompt: "Video games are now one of the most popular leisure activities for children and teenagers. Do you think the benefits of playing video games outweigh the drawbacks? Give reasons for your answer with relevant examples. Write at least 250 words.",
  },
  {
    topic: "entertainment_leisure",
    level: "advanced",
    examType: "ielts_task2",
    title: "Essay: Streaming and the Decline of Cinema",
    description: "Argue both views on streaming vs. cinema.",
    examPrompt: "Some argue that the rise of streaming services has irreversibly damaged the cultural significance of the cinema experience, while others maintain that streaming has democratized access to film and expanded the diversity of stories available. Discuss both views and give your own opinion. Write at least 250 words.",
  },

  // ─── 11. nature_environment ───
  {
    topic: "nature_environment",
    level: "beginner",
    examType: "ielts_task1",
    title: "Line Chart: Global CO₂ Emissions, 1990–2020",
    description: "Describe trends in global emissions.",
    examPrompt: "The line chart below shows global CO₂ emissions (in billion tonnes) from four sectors (Energy, Industry, Transport, Agriculture) between 1990 and 2020. Summarise the information by selecting and reporting the main features, and make comparisons where relevant. Write at least 150 words.",
    imageUrl: chartUrl({
      type: "line",
      data: {
        labels: ["1990", "1995", "2000", "2005", "2010", "2015", "2020"],
        datasets: [
          { label: "Energy", data: [10, 11, 12, 14, 16, 17, 16], borderColor: COLORS[0], fill: false },
          { label: "Industry", data: [4, 4.5, 5, 6, 7, 7.5, 7], borderColor: COLORS[1], fill: false },
          { label: "Transport", data: [4, 4.5, 5, 5.5, 6, 6.5, 5.5], borderColor: COLORS[2], fill: false },
          { label: "Agriculture", data: [3, 3.2, 3.4, 3.6, 3.8, 4, 4.1], borderColor: COLORS[3], fill: false },
        ],
      },
      options: {
        title: { display: true, text: "Global CO₂ Emissions by Sector (billion tonnes), 1990-2020" },
      },
    }),
  },
  {
    topic: "nature_environment",
    level: "intermediate",
    examType: "ielts_task2",
    title: "Essay: Individual Action vs. Government Action on Climate",
    description: "Discuss who bears responsibility for climate change.",
    examPrompt: "Some people argue that addressing climate change is primarily the responsibility of governments and large corporations, while others believe that individuals must change their own behavior. To what extent do you agree with each view? Write at least 250 words.",
  },
  {
    topic: "nature_environment",
    level: "advanced",
    examType: "ielts_task2",
    title: "Essay: Economic Growth vs. Environmental Protection",
    description: "Argue both views on the growth-environment trade-off.",
    examPrompt: "Some argue that continued economic growth is incompatible with serious environmental protection, while others maintain that only economic prosperity provides the resources needed to address environmental challenges. Discuss both views and give your own opinion. Write at least 250 words.",
  },

  // ─── 12. science_technology ───
  {
    topic: "science_technology",
    level: "beginner",
    examType: "ielts_task1",
    title: "Bar Chart: Smartphone Ownership by Age Group",
    description: "Describe smartphone adoption across ages.",
    examPrompt: "The bar chart below shows the percentage of smartphone ownership across five age groups in two countries (Country X and Country Y) in 2024. Summarise the information by selecting and reporting the main features, and make comparisons where relevant. Write at least 150 words.",
    imageUrl: chartUrl({
      type: "bar",
      data: {
        labels: ["13-17", "18-29", "30-49", "50-64", "65+"],
        datasets: [
          { label: "Country X", data: [95, 98, 96, 88, 65], backgroundColor: COLORS[0] },
          { label: "Country Y", data: [82, 92, 85, 70, 38], backgroundColor: COLORS[2] },
        ],
      },
      options: {
        title: { display: true, text: "Smartphone Ownership by Age Group (%, 2024)" },
        scales: { yAxes: [{ ticks: { beginAtZero: true, max: 100 } }] },
      },
    }),
  },
  {
    topic: "science_technology",
    level: "intermediate",
    examType: "ielts_task2",
    title: "Essay: Artificial Intelligence and Jobs",
    description: "Discuss AI's effect on employment.",
    examPrompt: "Artificial intelligence is increasingly capable of performing tasks once requiring human workers. Do you think governments should intervene to protect jobs, or should the workforce simply adapt to the new technology? Write at least 250 words.",
  },
  {
    topic: "science_technology",
    level: "advanced",
    examType: "ielts_task2",
    title: "Essay: Regulating Emerging Technologies",
    description: "Argue both views on regulating AI and biotech.",
    examPrompt: "Some argue that emerging technologies such as artificial intelligence and genetic engineering require strict government regulation to avoid serious harm, while others maintain that overregulation will stifle innovation and put nations at a competitive disadvantage. Discuss both views and give your own opinion. Write at least 250 words.",
  },

  // ─── 13. culture_society ───
  {
    topic: "culture_society",
    level: "beginner",
    examType: "ielts_task1",
    title: "Bar Chart: Festival Attendance by Region",
    description: "Describe festival attendance figures.",
    examPrompt: "The bar chart below shows the average number of people (in thousands) attending traditional festivals each year in four regions of a country in 2014 and 2024. Summarise the information by selecting and reporting the main features, and make comparisons where relevant. Write at least 150 words.",
    imageUrl: chartUrl({
      type: "bar",
      data: {
        labels: ["North", "Central", "South", "Highlands"],
        datasets: [
          { label: "2014", data: [120, 95, 140, 45], backgroundColor: COLORS[0] },
          { label: "2024", data: [180, 150, 210, 88], backgroundColor: COLORS[2] },
        ],
      },
      options: {
        title: { display: true, text: "Festival Attendance by Region (thousands)" },
      },
    }),
  },
  {
    topic: "culture_society",
    level: "intermediate",
    examType: "ielts_task2",
    title: "Essay: Preserving Traditional Culture",
    description: "Discuss how to preserve culture in a globalized world.",
    examPrompt: "As countries become more interconnected, many traditional cultural practices are being lost. What can individuals, schools, and governments do to help preserve cultural heritage in a globalized world? Write at least 250 words.",
  },
  {
    topic: "culture_society",
    level: "advanced",
    examType: "ielts_task2",
    title: "Essay: Multicultural Societies — Strength or Tension?",
    description: "Argue both views on multiculturalism.",
    examPrompt: "Some argue that multicultural societies are inherently more dynamic and innovative, while others contend that they often generate social tensions and weakened national identity. Discuss both views and give your own opinion. Write at least 250 words.",
  },

  // ─── 14. government_politics ───
  {
    topic: "government_politics",
    level: "beginner",
    examType: "ielts_task1",
    title: "Bar Chart: Voter Turnout in Four Countries",
    description: "Describe voter turnout figures.",
    examPrompt: "The bar chart below shows voter turnout (as a percentage of eligible voters) in national elections of four countries in 2000, 2010, and 2020. Summarise the information by selecting and reporting the main features, and make comparisons where relevant. Write at least 150 words.",
    imageUrl: chartUrl({
      type: "bar",
      data: {
        labels: ["Country A", "Country B", "Country C", "Country D"],
        datasets: [
          { label: "2000", data: [72, 58, 65, 48], backgroundColor: COLORS[0] },
          { label: "2010", data: [68, 62, 60, 52], backgroundColor: COLORS[1] },
          { label: "2020", data: [78, 55, 52, 56], backgroundColor: COLORS[2] },
        ],
      },
      options: {
        title: { display: true, text: "Voter Turnout in National Elections (%)" },
        scales: { yAxes: [{ ticks: { beginAtZero: true, max: 100 } }] },
      },
    }),
  },
  {
    topic: "government_politics",
    level: "intermediate",
    examType: "ielts_task2",
    title: "Essay: Compulsory Voting",
    description: "Discuss whether voting should be compulsory.",
    examPrompt: "Some countries have introduced compulsory voting in national elections. Do you think the benefits of mandatory voting outweigh the drawbacks of forcing citizens to participate? Give reasons for your answer. Write at least 250 words.",
  },
  {
    topic: "government_politics",
    level: "advanced",
    examType: "ielts_task2",
    title: "Essay: Direct Democracy vs. Representative Democracy",
    description: "Argue both views on direct vs. representative democracy.",
    examPrompt: "Some argue that direct democracy through frequent referendums brings government closer to the people, while others insist that complex policy decisions require the deliberation that only elected representatives can provide. Discuss both views and give your own opinion. Write at least 250 words.",
  },

  // ─── 15. history_geography ───
  {
    topic: "history_geography",
    level: "beginner",
    examType: "ielts_task1",
    title: "Bar Chart: Visitors to Historical Sites in Four Countries",
    description: "Describe tourist visits to historical sites.",
    examPrompt: "The bar chart below shows the number of visitors (in millions) to the most visited historical site in each of four countries in 2014 and 2024. Summarise the information by selecting and reporting the main features, and make comparisons where relevant. Write at least 150 words.",
    imageUrl: chartUrl({
      type: "bar",
      data: {
        labels: ["Italy", "Egypt", "Vietnam", "Peru"],
        datasets: [
          { label: "2014", data: [6.5, 11.2, 1.8, 1.2], backgroundColor: COLORS[0] },
          { label: "2024", data: [8.2, 14.5, 4.3, 1.9], backgroundColor: COLORS[2] },
        ],
      },
      options: {
        title: { display: true, text: "Visitors to Top Historical Sites (millions)" },
      },
    }),
  },
  {
    topic: "history_geography",
    level: "intermediate",
    examType: "ielts_task2",
    title: "Essay: Studying History in Schools",
    description: "Discuss the importance of teaching history.",
    examPrompt: "Some people believe that the study of history is essential for understanding the modern world, while others argue that schools should focus on more practical subjects. To what extent do you agree with each view? Write at least 250 words.",
  },
  {
    topic: "history_geography",
    level: "advanced",
    examType: "ielts_task2",
    title: "Essay: Preserving Historical Sites in Growing Cities",
    description: "Argue both views on heritage vs. urban development.",
    examPrompt: "Some argue that preserving historical sites in growing cities is essential for cultural identity, while others maintain that economic development must take precedence over heritage protection. Discuss both views and give your own opinion. Write at least 250 words.",
  },

  // ─── 16. sports_fitness ───
  {
    topic: "sports_fitness",
    level: "beginner",
    examType: "ielts_task1",
    title: "Bar Chart: Most Popular Sports by Country",
    description: "Describe popular sports in four countries.",
    examPrompt: "The bar chart below shows the percentage of adults who regularly participate in five sports (Football, Basketball, Tennis, Cycling, Swimming) in four countries in 2024. Summarise the information by selecting and reporting the main features, and make comparisons where relevant. Write at least 150 words.",
    imageUrl: chartUrl({
      type: "bar",
      data: {
        labels: ["Football", "Basketball", "Tennis", "Cycling", "Swimming"],
        datasets: [
          { label: "UK", data: [28, 12, 18, 22, 20], backgroundColor: COLORS[0] },
          { label: "USA", data: [10, 32, 15, 14, 24], backgroundColor: COLORS[1] },
          { label: "Brazil", data: [55, 18, 8, 12, 16], backgroundColor: COLORS[2] },
          { label: "Japan", data: [20, 14, 12, 28, 18], backgroundColor: COLORS[3] },
        ],
      },
      options: {
        title: { display: true, text: "Adult Participation in Sports by Country (%, 2024)" },
      },
    }),
  },
  {
    topic: "sports_fitness",
    level: "intermediate",
    examType: "ielts_task2",
    title: "Essay: Salaries of Professional Athletes",
    description: "Discuss the high pay of top athletes.",
    examPrompt: "Top professional athletes are paid enormous salaries, often far more than people in essential professions. Do you think their salaries are justified, or should they be regulated? Give reasons for your answer. Write at least 250 words.",
  },
  {
    topic: "sports_fitness",
    level: "advanced",
    examType: "ielts_task2",
    title: "Essay: Competitive Sport in Childhood",
    description: "Argue both views on competitive youth sport.",
    examPrompt: "Some argue that introducing children to highly competitive sports builds resilience and ambition, while others maintain that early competitive pressure causes lasting psychological harm. Discuss both views and give your own opinion. Write at least 250 words.",
  },

  // ─── 17. arts_literature ───
  {
    topic: "arts_literature",
    level: "beginner",
    examType: "ielts_task1",
    title: "Bar Chart: Museum Visits in Five European Cities",
    description: "Describe museum visit figures.",
    examPrompt: "The bar chart below shows the number of annual museum visits (in millions) in five European cities in 2014 and 2024. Summarise the information by selecting and reporting the main features, and make comparisons where relevant. Write at least 150 words.",
    imageUrl: chartUrl({
      type: "bar",
      data: {
        labels: ["Paris", "London", "Rome", "Amsterdam", "Berlin"],
        datasets: [
          { label: "2014", data: [12.5, 11.8, 6.2, 4.5, 5.8], backgroundColor: COLORS[0] },
          { label: "2024", data: [16.2, 14.3, 8.5, 6.1, 7.2], backgroundColor: COLORS[2] },
        ],
      },
      options: {
        title: { display: true, text: "Annual Museum Visits (millions)" },
      },
    }),
  },
  {
    topic: "arts_literature",
    level: "intermediate",
    examType: "ielts_task2",
    title: "Essay: Public Funding for the Arts",
    description: "Discuss whether the arts should receive public funding.",
    examPrompt: "Some people believe that governments should provide substantial funding to museums, theatres, and other arts institutions, while others argue that such money is better spent on essential services. Discuss both views and give your own opinion. Write at least 250 words.",
  },
  {
    topic: "arts_literature",
    level: "advanced",
    examType: "ielts_task2",
    title: "Essay: Reading Literature in the Digital Age",
    description: "Argue both views on literature in the digital age.",
    examPrompt: "Some commentators argue that the rise of short-form digital content has fundamentally diminished the cultural role of long-form literature, while others maintain that literary fiction continues to flourish in new and unexpected formats. Discuss both views and give your own opinion. Write at least 250 words.",
  },

  // ─── 18. religion_spirituality ───
  {
    topic: "religion_spirituality",
    level: "beginner",
    examType: "ielts_task1",
    title: "Bar Chart: Religious Affiliation by Country",
    description: "Describe religious affiliation across countries.",
    examPrompt: "The bar chart below shows the percentage of the adult population identifying with various religious affiliations (Buddhist, Christian, Muslim, Hindu, No religion) in four countries in 2024. Summarise the information by selecting and reporting the main features, and make comparisons where relevant. Write at least 150 words.",
    imageUrl: chartUrl({
      type: "bar",
      data: {
        labels: ["Thailand", "Italy", "Indonesia", "India"],
        datasets: [
          { label: "Buddhist", data: [93, 1, 1, 8], backgroundColor: COLORS[0] },
          { label: "Christian", data: [1, 81, 10, 3], backgroundColor: COLORS[1] },
          { label: "Muslim", data: [4, 4, 86, 14], backgroundColor: COLORS[2] },
          { label: "Hindu", data: [0, 0, 1, 72], backgroundColor: COLORS[3] },
          { label: "No religion", data: [2, 14, 2, 3], backgroundColor: COLORS[4] },
        ],
      },
      options: {
        title: { display: true, text: "Religious Affiliation by Country (%, 2024)" },
        scales: { yAxes: [{ ticks: { beginAtZero: true, max: 100 } }] },
      },
    }),
  },
  {
    topic: "religion_spirituality",
    level: "intermediate",
    examType: "ielts_task2",
    title: "Essay: Religion in Public Schools",
    description: "Discuss the role of religious instruction in schools.",
    examPrompt: "Some people believe that religious studies should be taught in public schools to foster mutual understanding, while others argue that religion has no place in a secular education system. Discuss both views and give your own opinion. Write at least 250 words.",
  },
  {
    topic: "religion_spirituality",
    level: "advanced",
    examType: "ielts_task2",
    title: "Essay: Decline of Religion and Rise of Spirituality",
    description: "Argue both views on religion vs. modern spirituality.",
    examPrompt: "Some observers argue that organized religion is in long-term decline and that 'personal spirituality' is taking its place, while others contend that traditional religious institutions continue to provide essential community and moral structure. Discuss both views and give your own opinion. Write at least 250 words.",
  },

  // ─── 19. law_justice ───
  {
    topic: "law_justice",
    level: "beginner",
    examType: "ielts_task1",
    title: "Bar Chart: Crime Rates by Type",
    description: "Describe changes in crime statistics.",
    examPrompt: "The bar chart below shows the number of reported crimes per 10,000 people for five categories (Theft, Assault, Fraud, Vandalism, Cybercrime) in a country in 2010 and 2024. Summarise the information by selecting and reporting the main features, and make comparisons where relevant. Write at least 150 words.",
    imageUrl: chartUrl({
      type: "bar",
      data: {
        labels: ["Theft", "Assault", "Fraud", "Vandalism", "Cybercrime"],
        datasets: [
          { label: "2010", data: [85, 32, 18, 28, 5], backgroundColor: COLORS[0] },
          { label: "2024", data: [58, 28, 35, 22, 48], backgroundColor: COLORS[2] },
        ],
      },
      options: {
        title: { display: true, text: "Reported Crimes per 10,000 People" },
      },
    }),
  },
  {
    topic: "law_justice",
    level: "intermediate",
    examType: "ielts_task2",
    title: "Essay: Should Criminals Receive Education in Prison?",
    description: "Discuss rehabilitation programs in prisons.",
    examPrompt: "Some argue that prisons should focus on rehabilitation by offering education and training to inmates, while others believe that prisons should primarily punish criminals. Do you think rehabilitation should be the main goal of imprisonment? Give reasons for your answer. Write at least 250 words.",
  },
  {
    topic: "law_justice",
    level: "advanced",
    examType: "ielts_task2",
    title: "Essay: Surveillance and Civil Liberties",
    description: "Argue both views on state surveillance.",
    examPrompt: "Some argue that expanded state surveillance is necessary to prevent terrorism and serious crime, while others insist that such measures erode the civil liberties that define democratic societies. Discuss both views and give your own opinion. Write at least 250 words.",
  },

  // ─── 20. philosophy_ethics ───
  {
    topic: "philosophy_ethics",
    level: "beginner",
    examType: "ielts_task1",
    title: "Bar Chart: Values Considered Most Important by Generation",
    description: "Describe top values across generations.",
    examPrompt: "The bar chart below shows the percentage of respondents from three generations (Baby Boomers, Gen X, Gen Z) who rated five values (Honesty, Family, Career success, Freedom, Equality) as 'most important' in 2024. Summarise the information by selecting and reporting the main features, and make comparisons where relevant. Write at least 150 words.",
    imageUrl: chartUrl({
      type: "bar",
      data: {
        labels: ["Honesty", "Family", "Career success", "Freedom", "Equality"],
        datasets: [
          { label: "Baby Boomers", data: [72, 80, 45, 55, 38], backgroundColor: COLORS[0] },
          { label: "Gen X", data: [68, 65, 60, 62, 48], backgroundColor: COLORS[1] },
          { label: "Gen Z", data: [55, 48, 42, 75, 78], backgroundColor: COLORS[2] },
        ],
      },
      options: {
        title: { display: true, text: "Values Rated 'Most Important' by Generation (%, 2024)" },
        scales: { yAxes: [{ ticks: { beginAtZero: true, max: 100 } }] },
      },
    }),
  },
  {
    topic: "philosophy_ethics",
    level: "intermediate",
    examType: "ielts_task2",
    title: "Essay: Honesty in Modern Society",
    description: "Discuss the value of honesty in everyday life.",
    examPrompt: "Some people believe that absolute honesty is always the best policy, while others argue that small lies are sometimes necessary to maintain social harmony. To what extent do you agree with each view? Write at least 250 words.",
  },
  {
    topic: "philosophy_ethics",
    level: "advanced",
    examType: "ielts_task2",
    title: "Essay: The Ethics of AI Decision-Making",
    description: "Argue both views on AI making moral decisions.",
    examPrompt: "Some argue that artificial intelligence can never make truly ethical decisions because it lacks human consciousness and lived experience, while others contend that data-driven AI can be more consistent and fair than human judgment. Discuss both views and give your own opinion. Write at least 250 words.",
  },
];

function buildBody(entry) {
  const body = {
    title: entry.title,
    level: entry.level,
    topic: entry.topic,
    description: entry.description,
    examType: entry.examType,
    examPrompt: entry.examPrompt,
  };
  if (entry.imageUrl) body.imageUrl = entry.imageUrl;
  return body;
}

async function runUpdateImages() {
  console.log("Mode: UPDATE_IMAGES (patch imageUrl on existing exams)\n");
  let updated = 0;
  let missing = 0;
  let unchanged = 0;
  let failed = 0;

  for (const entry of EXAMS) {
    if (!entry.imageUrl) continue;
    try {
      const result = await Exam.updateOne(
        { title: entry.title, imageUrl: { $ne: entry.imageUrl } },
        { $set: { imageUrl: entry.imageUrl } },
      );
      if (result.matchedCount === 0) {
        const exists = await Exam.exists({ title: entry.title });
        if (exists) {
          unchanged++;
          console.log(`SAME  ${entry.title}`);
        } else {
          missing++;
          console.log(`MISS  ${entry.title} (no exam with this title)`);
        }
      } else {
        updated++;
        console.log(`UPD   ${entry.title}`);
      }
    } catch (err) {
      failed++;
      console.error(`FAIL  ${entry.title}: ${err.message}`);
    }
  }

  console.log(
    `\nSummary: updated=${updated}, unchanged=${unchanged}, missing=${missing}, failed=${failed}`,
  );
}

async function run() {
  await CONNECT_DB();

  if (UPDATE_IMAGES) {
    await runUpdateImages();
    await mongoose.disconnect();
    return;
  }

  console.log(
    `Mode: ${FORCE ? "FORCE (allow duplicate titles)" : "DEDUPE by title"}`,
  );
  console.log(`Planning ${EXAMS.length} exams.\n`);

  let created = 0;
  let skipped = 0;
  let failed = 0;

  for (const entry of EXAMS) {
    try {
      if (!FORCE) {
        const exists = await Exam.exists({ title: entry.title });
        if (exists) {
          skipped++;
          console.log(`SKIP  [${entry.level}/${entry.examType}] ${entry.title}`);
          continue;
        }
      }
      const exam = await createExam(buildBody(entry));
      created++;
      console.log(
        `OK    [${entry.level}/${entry.examType}] ${entry.title} → ${exam._id}`,
      );
    } catch (err) {
      failed++;
      console.error(`FAIL  ${entry.title}: ${err.message}`);
    }
  }

  console.log(
    `\nSummary: created=${created}, skipped=${skipped}, failed=${failed}`,
  );
  await mongoose.disconnect();
}

run().catch((e) => {
  console.error(e);
  process.exit(1);
});
